### ISSUE TITLE
mangled site pages are appearing on the production site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1014]
Go to a page like https://docs-preview.newrelic.com/docs/mobile-monitoring/mobile-monitoring-ui/mobile-app-pages/mobile-apps-index

and view the page, all content is being mangled. to resolve add a `/` to the page URL, and it corrects the problem, but this is  occurring on other pages as well after you are stuck in this broken state. Once you are stuck in this broken state, the entire seems seems to stay mangled as you traverse the site. 

<img width="1492" alt="Screen Shot 2021-02-26 at 4 22 21 PM" src="https://user-images.githubusercontent.com/1395158/109365733-1bdab680-784f-11eb-9eda-a52479d42fe4.png">

**Comment by jpvajda** [comment]
waiting on next build, which could fix this 🤞

**Comment by jpvajda** [comment]
The problem of mangle pages seems to be only triggered by 3 pages, and we have a fix for it. to add trailing `/`

**Comment by jerelmiller** [comment]
We've got a PR open that forces trailing slashes everywhere (#1205), however this doesn't solve the problem entirely. That PR does make it so the nav links to the page with a trailing slash, so unless a customer navigates to the page in their browser without the trailing slash, they shouldn't stumble upon this naturally.

The more I dug into this, the more I see a pattern with these pages. All of the mangled pages ended with a `-index` suffix in the page URL. I think Amplify is doing something strange with this particular name and causing our weird mangled pages.

I've queried the local GraphQL schema for the docs site and looks like there are 5 pages with such a name. Since this appears to be an issue with Amplify, I opened an issue over there: https://github.com/aws-amplify/amplify-console/issues/1629. We'll keep tabs on that issue and see if there is something they need to fix or if there is some redirect configuration we can fix on our end.
