### ISSUE TITLE
There are random docs in the docs directory

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#1023]
### Description

The `src/content/docs` directory has a bunch of free floating docs. We should figure out where these docs should actually live and figure out if this is an eng bug or something docs writers should take care of.

### Steps to reproduce

1. Go to `src/content/docs`
2. The free floating docs are mixed in with the rest of the taxonomy. 

### Expected behavior

There should only be directories, no free-floating docs. 

cc @austin-schaefer

**Comment by jerelmiller** [comment]
I'm actually not sure I'd label this as a bug, but maybe more of a stylistic thing. The reason this are in the `docs` folder is because those URLs live there.

If we'd rather have folders only in `src/content/docs`, but want to keep the URL, one thing you can do is create `index.mdx` files for each of these in a folder named the same as the file now. For example, if you wanted to move [`src/content/docs/adduserattribute-python-agent-api.mdx`](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/adduserattribute-python-agent-api.mdx) to a folder, then we could stick that in `src/content/docs/adduserattribute-python-agent-api/index.mdx` and it would maintain the same URL

**Comment by bradleycamacho** [comment]
Thanks for clarify, I'll get to work on this next week! I'll remove the `eng` and `bug` labels in that case.

**Comment by austin-schaefer** [comment]
For reference, there are 29 of these orphaned files right now:

* adduserattribute-python-agent-api.mdx
* archive-campfire-example.mdx
* archive-locate-exact-metric-names.mdx
* automated-user-management-Introduction.mdx
* azure-cosmos-db-document-db-monitoring-integration-deprecated.mdx
* cloud-instance-optimizer-find-underused-virtual-machines.mdx
* correlate-load-balancer-application-metrics-workloads.mdx
* csp-v2-error-inline-javascript-not-allowed.mdx
* csp-v2-host-install-browser-agent.mdx
* csp-v2-monitor-salesforce.mdx
* fedramp-endpoint-logs-metrics.mdx
* gateway-api-import-data-other-observability-platforms.mdx
* insights-usage-ui-page.mdx
* instrument-errors-c-sdk.mdx
* instrument-transactions-c-sdk.mdx
* instrumentation-editor-instrument-net-ui.mdx
* introduction-new-relic-agent-sdk.mdx
* introduction-new-relic-mobile-unity.mdx
* ios-device-id-obfuscation.mdx
* mobile-crash-rest-api-v1.mdx
* net-agent-install-resources.mdx
* new-relic-titanium.mdx
* okta-scim-assign-users-automated-provisioning-beta.mdx
* prometheus-remote-write-integration.mdx
* python-agent-api-different-call-forms.mdx
* recommended-alerts-aws-services.mdx
* upgrade-beta-rootless-agent-ga.mdx
* verify-your-alerts-after-activating-remote-monitoring.mdx
* windows-services-integration.mdx

**Comment by rhetoric101** [comment]
This work is slated for an upcoming sprint in DOC-6956.

**Comment by bradleycamacho** [comment]
Closed in Doc-7105
