### ISSUE TITLE
Feedback: FedRAMP-compliant endpoints

### ISSUE THREAD

**Issue by rajumkc** [newrelic/docs-website#1059]
### Tell us more about your feedback

Can you provide a  "Change History" section for the page?. I could see some new entries which I didn't see a week back.

* What worked well in this doc?
* How could we make this doc even better?
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/security/security-privacy/compliance/fedramp-compliant-endpoints
* **OS**: Mac OS 11.2.1
* **Browser**: Chrome 88.0.4324.150
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
Hi @rajumkc ! You can actually see the change history for any doc in the GitHub commit logs, but only for the time since we launched our new GitHub-based docs site (which is today, so alas no history in GitHub for this doc). I took a look at the history of this doc in the old CMS and the only change I saw recently was a tweak on February 4:

![image](https://user-images.githubusercontent.com/55203603/109565031-be38ab00-7a96-11eb-95ab-263a8cb20a69.png)

The easiest way to see the history for future changes is to click the **Edit page** button on a doc. That'll bounce you over to Github, and from there you can just click **History** and see the full change history for that doc.

![image](https://user-images.githubusercontent.com/55203603/109564506-03a8a880-7a96-11eb-8b7f-e9d19759a460.png)

**Comment by austin-schaefer** [comment]
Closed this issue for now @rajumkc but feel free to comment or re-open if needed!
