### ISSUE TITLE
Remove apdex_t as an option that can be configured in the agent configuration file

### ISSUE THREAD

**Issue by mfahmy888** [newrelic/docs-website#10686]
It's confusing to have [apdex_t listed as an option](https://docs.newrelic.com/docs/apm/agents/python-agent/configuration/python-agent-configuration/#apdex-t) that can be configured in the Python agent configuration file when in reality Apdex T can only be [configured via application settings](https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/apdex-measure-user-satisfaction/#apm-apdex) in the UI. Please see this New Relic [discussion post](https://discuss.newrelic.com/t/apdex-t-in-agent-config-file-not-consistent-with-what-shows-up-in-our-apm/191684/3) for context

**Comment by rhetoric101** [comment]
@mfahmy888 thanks for your input! I'm checking with our Python SMEs to see what they think.

**Comment by hmstepanek** [comment]
In `serverless_mode` which is enabled for AWS Lambda, the local `apdex_t` value is used to set the `apdex_f` value. When `serverless_mode` is disabled, you are correct, the local `apdex_t` value is overridden by the value in UI application settings and that is then used to set the `apdex_f` value. The docs do not explain this, so I think we could definitely clarify that. We should not remove this setting entirely though, since it is still used in serverless mode.
