### ISSUE TITLE
[IA Research] Determine directory structure for content

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#11]
## Summary

There are over 5,000 markdown files that will be in the documentation site. We need to figure out a way to structure this content in our repository.

## Procedure

Open up a PR merging into `research`. If there is no changes in the code (and only research details), you can just make an edit in a text file, since there is no plan to merge this into `main`.  Use the PR template [research_PR_template.md](https://github.com/newrelic/docs-website/blob/main/.github/PULL_REQUEST_TEMPLATE/research_PR_template.md) either by coping the markdown into the PR or by appending the query string `?template=research_PR_template.md` to the URL. Fill out the template by answering the research questions listed below. 

## Research Goals

* [ ] Determine a file structure for content (is it determined by folder, by frontmatter ect.) 
* [ ] Discuss solutions with engineers, content creators and PMs to determine best path forward

**Comment by zstix** [comment]
We spoke with some stakeholders and evaluated a few options. We have decided that we do _not_ want to store all markdown files within a single directory. We would like to either make a fully-nested structure that mimics the category hierarchy _or_ make a single-level structure where we have top-level category buckets.

Moving forward, we are going to try to migrate some content with one of these strategies and re-evaluate. I'm going to move this ticket to the next MMF, since that is when we will do that evaluation.
