### ISSUE TITLE
Add FutureStack banner/tile to homepage

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#1173]
### Is your feature request related to a problem? Please describe

We want to include a CTA for FutureStack on the docs homepage. I think we'd like to avoid using the site-wide announcemtent banner to start to avoid alert fatigue. I'm filing this as an `eng` issue b/c I suspect writers can take an initial crack at this but might need some support from the dev team on adding a new section to the homepage.

### Describe the solution you'd like

A callout-like banner across homepage, probably below the 1,2,3 and above TDP.

@austin-schaefer is working with the marketing folks on the copy.

### Additional context

Registrations are open now, so getting this up in the next week or two should be our target.

**Comment by jerelmiller** [comment]
It would be great to understand the design requirements for this as well. Let's see if we can pull in some help from XD to get us a nice looking announcement banner. 

In making this change, I think it would also be beneficial to start creating rules about when we use the site-wide banner vs this new announcement format, otherwise I could see us delving into confusion and chaos pretty quickly. 

Something also to consider: is this a design pattern we can use on other sites? Or will this need to be docs-specific?

**Comment by austin-schaefer** [comment]
This was fixed in #2084
