### ISSUE TITLE
StorageSample Event type explanatory data is incorrect

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#1182]
Hello! 

https://docs.newrelic.com/attribute-dictionary/?event=StorageSample 

inodesTotal Definition is incorrect.

**Comment by jerelmiller** [comment]
Hey @dralph3344! We've got all of our attribute dictionary definitions in this repo as well. If you've got a good idea on what that should be, feel free to edit them! For reference here is the file that contains the definition for `inodesTotal`

https://github.com/newrelic/docs-website/blob/develop/src/data-dictionary/events/StorageSample/inodesTotal.md

Feel free to submit a PR if you've got an idea on how to change. Otherwise, would you be willing to provide a better understanding of what is incorrect about this definition so that our docs team can help provide guidance on how to proceed?

**Comment by dralph3344** [comment]
Hi team, I cant recall what particularly what the issue was with the definition. Potentially the inclusion of "available" in the definition was not ideal. We can close this up for now.
