### ISSUE TITLE
set proptypes for create issue on docs site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1206]
see https://github.com/newrelic/gatsby-theme-newrelic/pull/311 for details on the new prop top available in the create issue button to set the label to be used when filing an issue. 

with this new prop we can set the label to be used on each site's create issue button, We should set the following once all sites are bumped to this theme version.

Note: OSS / Dev will default to bug, if no prop is set. 

- OSS: bug
- DEV: bug
- Docs: feedback, feedback-issue

**Comment by jerelmiller** [comment]
NOTE: The `bug` is the default label applied if the prop is not defined. For now we should be ok just updating docs.

**Comment by jpvajda** [comment]
This change requires a theme update on the Docs Site.

**Comment by jpvajda** [comment]
@jerelmiller where do we set this prop on the docs site? I was looking for a place to set that and wasn't sure where it's applied.

**Comment by jerelmiller** [comment]
We had [one more PR](https://github.com/newrelic/gatsby-theme-newrelic/pull/318) that added a prop to forward the `issues` from `ContributingGuidelines` -> `CreateIssueButton`. You'll need to update the [`docPage.js`](https://github.com/newrelic/docs-website/blob/develop/src/templates/docPage.js#L113-L116) template's `ContributingGuidelines` and add a prop for the labels:

```js
<ContributingGuidelines
  pageTitle={title}
  fileRelativePath={fileRelativePath}
  issueLabels={['feedback', 'feedback-content']} // <---- This is new
/>
```

I can't remember the exact label names, but you want that above. Looks like the [attribute dictionary](https://github.com/newrelic/docs-website/blob/338a880f0789f77a86f142d57d9898736573a0d6/src/pages/attribute-dictionary.js#L168) page also uses this component, so that will need to be updated as well.

**Comment by jpvajda** [comment]
I have one more change to make: in the global footer we also have this button functionality. I'll have to add a prop to this component. 

https://github.com/newrelic/gatsby-theme-newrelic/blob/a07dd9eaa19a85b1e0bdda32aaa7f5b272aa8fd2/packages/gatsby-theme-newrelic/src/components/GlobalFooter.js#L86

**Comment by jpvajda** [comment]
So this is 90% done....

I'm struggling to locate where to set prop value on the docs site global footer's create issue button, I know what prop to set `issueLabels={['feedback', 'feedback-issue']}` just not clear where to set that. 

In the global footer in theme if i set the prop value there won't all sites then use these? we only want to the doc site create issue button to use the labels above, all other sites would use the default value of `bug.` -- @zstix / @roadlittledawn

**Comment by jpvajda** [comment]
From @LizBaker  looks like we’ll need to add an optional issueLabels prop to the global footer so it can pass those through to the button. same as what was done for the ContributingGuidelines component [here] (https://github.com/newrelic/gatsby-theme-newrelic/pull/318)
