### ISSUE TITLE
Correct blocks of code in Docs that lack syntax highlighting

### ISSUE THREAD

**Issue by viglucci** [newrelic/docs-website#1218]
### Issue

Syntax highlighting code examples would make them easier to understand. Code without syntax highlighting often just looks like a big blob of text, we've all gotten used to highlighting in our editors/IDEs and tend to look for certain patterns via highlighting/colors.

![image](https://user-images.githubusercontent.com/6305490/110346731-75807500-7ff5-11eb-8b43-f7bdb54257f6.png)

Compared to:

![image](https://user-images.githubusercontent.com/6305490/110346854-9943bb00-7ff5-11eb-89fd-d7c9893c905d.png)

### The fix

```
```js    <--- this is needed in the code block syntax
// ...
```

### Acceptance Criteria

- all code blocks in documentation should ideally have the correct syntax value set to allow the block to provide syntax highlighting. 
-  this can be done by content writers as the come across these blocks in documentation

### about automation
-  programmatically it may be difficult to try to do this as there are many blocks of code and many types of blocks, given all the variables trying to script this may not be easy to get this right. So it's proposed we just do this manually as we come across blocks that lack the correct syntax value type for each code block.

**Comment by jpvajda** [comment]
@viglucci totally agree! we accept PRs so if you want to contribute to the project our codeblock component code can be found here: https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/CodeBlock.js

**Comment by viglucci** [comment]
Thanks for the direction to the file @jpvajda . If this doesn't receive community contribution I am assuming that this is still potentially something New Relic could/would invest in implementing given the proper prioritizationn?

**Comment by jerelmiller** [comment]
@viglucci I can weigh in here. We do have syntax highlighting setup for all code blocks via our theme, but it requires a language specification to do so, otherwise it shows a single text color. We use [Prism.js](https://prismjs.com/) to handle syntax highlighting our code blocks. We currently have support for the following languages:

- css/sass/scss
- hcl
- javascript/jsx
- json
- ruby
- shell/bash
- sql
- graphql
- yaml
- xml
- xml-doc
- c
- go
- java
- php
- phpdoc
- csharp
- python

Our old docs site didn't have much syntax highlighting in code blocks, so when we migrated over to our new site, many of the code blocks did not get language specifiers. If you'd like to contribute a change, I think all we'd need is to add a language specifier to the fenced code blocks on docs that do not have them.

````
```js    <--- this is needed
// ...
```
````

Again, feel free to contribute a quick change to the docs in question if you'd like to see some syntax highlighting and we will see what we can do to make this more globally available in our docs going forward. Thanks for raising this issue as I agree that syntax highlighting would do a lot for our docs!

**Comment by jpvajda** [comment]
This issue isn't an engineering bug, more so a content issue where certain code  blocks in docs don't use the correct syntax definitions in the block, so I'll mark it as content. 

```js    <--- this is needed
// ...
```

**Comment by rhetoric101** [comment]
@viglucci, we created Jira DOC-6972 to inventory our doc site code samples and add the type.

**Comment by viglucci** [comment]
@rhetoric101 thanks for the update! For transparency, I've moved on from my previous employer where I was using NR heavily, and at the moment I am not actively leveraging any NR products, so it is unlikely I will be as invested in this issue/the documentation in the short term.

**Comment by austin-schaefer** [comment]
Talking in our team meeting about how to do this, where to do it, and how to ensure writers are taking this into account for new projects. Closing out the ticket but appreciate the feedback!
