### ISSUE TITLE
Issue: Get started with Incident Intelligence

### ISSUE THREAD

**Issue by wrekone** [newrelic/docs-website#1259]
### Tell us what you need

The screenshots on this page are low resolution and not expandable, making it hard to correlate the documentation to the elements in the screenshots.

### Anything else you'd like to share?

I'm viewing this on a 4k screen, so I would expect the embedded images to appear small. However, I should be able to click on an image and view it at full resolution.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/get-started-incident-intelligence/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by mmfred** [comment]
Hi @wrekone - thank you for your feedback -- we have an open issue to develop the ability to click an image and view it full size. That's [issue #850](https://github.com/newrelic/docs-website/issues/850).  I'll link this issue to that one to support this ongoing need. I'm reluctant to change the screenshot, though, because I'm hopeful it will be addressed when this feature is developed. (Also, this problem is pervasive throughout the docs until we get the ability to expand. )
