### ISSUE TITLE
[Nav UI] Add a search box and filter results 

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#133]
# Description 
We will want to add a search box and filter results, similar to how we have it on the developer site. We want the search box to only appear on the top-level navigation and to only filter under the top-level navigation.

## Acceptance Criteria
* [ ] Search box rendered under the top level and nested nav view 
* [ ] Search box filters results for that top level navigation/
* [ ] Matching elements to the search results are shown in bold
* [ ] Search box has the ability to clear input
* [ ] Search box works in mobile menu

## Screenshot(s)
![Screen Shot 2020-10-16 at 5 26 33 PM](https://user-images.githubusercontent.com/1946433/96324218-79274700-0fd5-11eb-8fbb-676380e02fcd.png)

**Comment by zstix** [comment]
When we discussed this feature in the MMF4 kickoff meeting, we realized that we had not decided if we want the search to filter pages in the current nav ("Full Stack Observability" in the screenshots above) or to filter _all_ pages on the site.

Since this was an open question with some technical implications, we decided to punt on this work.
