### ISSUE TITLE
signup_click event no longer occuring

### ISSUE THREAD

**Issue by tariqahmed** [newrelic/docs-website#1335]
The signup_click event appears to no longer be firing/tracked.

The last occurrence of this was on March 4th.
`SELECT * FROM PageAction where actionName ='signup_click' and appName ='docs.newrelic.com' since 2 weeks ago `

OR For a  time series view

`SELECT count(*) as 'Sign Ups' FROM PageAction where actionName ='signup_click' and appName ='docs.newrelic.com' since 1 month ago timeseries 1 day COMPARE WITH 2 months ago limit max`

Though this query does return event data

`SELECT count(*) AS 'Signups' FROM TessenAction WHERE nr_product = 'DOC' AND eventName = 'TDOC_DocPageLinkClick_stitchedPathLinkClick' SINCE 1 day ago`

**Comment by tariqahmed** [comment]
@jpvajda - FYI

**Comment by jpvajda** [comment]
We seems to be tracking the signup event in GA correctly, so I'm curious what may be the issue within New Relic causing this problem.

**Comment by jpvajda** [comment]
<img width="1331" alt="Screen Shot 2021-03-15 at 2 35 13 PM" src="https://user-images.githubusercontent.com/1395158/111217918-b8b18980-859b-11eb-8d68-ada61f1848d1.png">
<img width="1617" alt="Screen Shot 2021-03-15 at 2 35 21 PM" src="https://user-images.githubusercontent.com/1395158/111217927-b9e2b680-859b-11eb-8daf-cbe4fe39a972.png">

**Comment by jpvajda** [comment]
Looking at Segment I see these events firing from the docs site.  I don't see an event called `signup_click`

<img width="735" alt="Screen Shot 2021-03-15 at 3 15 10 PM" src="https://user-images.githubusercontent.com/1395158/111222338-52c80080-85a1-11eb-8bbf-4991beb37aa5.png">

**Comment by jerelmiller** [comment]
@tariqahmed @jpvajda If I remember correctly, `signup_click` no longer exists since we aren't instrumenting sign up clicks with NR Browser. The sign up clicks are only instrumented via Tessen.

To see the raw tessen data, I believe you'll have to switch to the Tessen account and check that way. I see the following code in our [sign up link](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/SignUpLink.js#L54-L58):

```js
        tessen.track('stitchedPathLinkClick', 'DocPageLinkClick', {
          href,
          path: location.pathname,
          component: instrumentation?.component,
        });
```

Should be under an action as something like `TDOC_DocPageLinkClick_stitchedPathLinkClick` (if I'm remembering the order of how Tessen stitches that name together 😆.

cc @zstix

**Comment by jpvajda** [comment]
adding to @jerelmiller we also documented all the events and action names for clarity: https://github.com/newrelic/docs-website/wiki/Event-Data--and--Instrumentation

**Comment by jpvajda** [comment]
It's still not clear to me what GA is measuring, it's an event called `Sign Up`

<img width="787" alt="Screen Shot 2021-03-15 at 4 08 11 PM" src="https://user-images.githubusercontent.com/1395158/111227778-b0ac1680-85a8-11eb-9508-46fe900b6d20.png">

**Comment by jpvajda** [comment]
@tariqahmed apart from my question on what is GA actually tracking(which isn't necessarily related) I think the solution to this problem is the change your queries to use the tessen events and track the stiched path [events documented here].(https://github.com/newrelic/docs-website/wiki/Event-Data--and--Instrumentation)

```
SELECT count(*) AS 'Signups' FROM TessenAction WHERE nr_product = 'DOC' AND eventName = 'TDOC_DocPageLinkClick_stitchedPathLinkClick' SINCE 1 day ago
```

**Comment by tariqahmed** [comment]
`SELECT count(*) AS 'Signups' FROM TessenAction WHERE nr_product = 'DOC' AND eventName = 'TDOC_DocPageLinkClick_stitchedPathLinkClick' SINCE 1 day ago`

^^ Shows 21

`SELECT count(*) FROM PageAction where appName = 'docs.newrelic.com' WHERE actionName = 'externalLink_click' and href like '%signup%' SINCE 1 day ago`

^^ Shows 71

The TessenAction's don't seem accurate. When I test by clicking on the Free Account button, I see them come in:

SELECT * FROM PageAction where appName = 'docs.newrelic.com' WHERE actionName = 'externalLink_click' and href like '%signup%' and city='Tracy' SINCE yesterday LIMIT 10

But I don't see them getting registered as a TessenAction:

SELECT * FROM TessenAction WHERE nr_product = 'DOC' AND eventName = 'TDOC_DocPageLinkClick_stitchedPathLinkClick' SINCE yesterday

Even created a new account. 

I was able to eventually get it to fire by going to
https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9140290/

And then clicking on "Free Account"

So if you hit the page fresh, and click on Free Account, the Tessen Action doesn't fire.

**Comment by jpvajda** [comment]
Interesting.. thanks for deducing this for us, I think I'm going to see if @caylahamann may have some insights here as she did a lot of work on this.. but I think this is a bug in our code. cc @zstix / @polfliet

**Comment by caylahamann** [comment]
Hey everyone! some context on this: 
### We removed the `signup_click` event from NR
The reason for this is that we weren't planning on tracking it on NR, the original intention was to track it as a Tessen event since it would be used by product analytics. Additionally, we were only tracking sign up clicks in the GlobalHeader. The changes we made track sign up links on the index page. There was some miscommunication in the original body of work, and it was rectified right after GA. 

### Reasons for why the data may be off: 
1. I'm seeing a super interesting error in the network tag while debugging. On the index page, when clicking on a link, we get a 414 error that the request URI is too large. You can see the event being tracked here:
<img width="1917" alt="Screen Shot 2021-03-17 at 4 54 20 PM" src="https://user-images.githubusercontent.com/38332422/111538615-4c718a00-8743-11eb-8134-dbbcdd46bad6.png">
But then an error occuring here (the red response):
<img width="1920" alt="Screen Shot 2021-03-17 at 5 04 49 PM" src="https://user-images.githubusercontent.com/38332422/111538663-56938880-8743-11eb-8308-f97a0697a210.png">

My guess is that somehow the tessen code is sending our page data and the data is too large? I'm not really sure what's going on. It seems to be a Tessen internal problem that we will probably have to do some further investigation on. It might also account for some of the discrepancies that we are seeing in page actions. A helpful tip to debug this is to add `Tessen.debugLevel(2)` somewhere in the code and then play around with Tessen actions. I can always do this, but as I'm no longer on the team definitely don't want to take work away 😄 

2. The cookie consent dialog! 

As mentioned previously, the cookie consent dialog (if not accepted) won't let any actions fire from tessen. We still track NR events (and we might need to reconsider if this is okay either because GDPR might not allow us too, it was little unclear in the conversation we had in the #gdpr channel, convo here: https://newrelic.slack.com/archives/C6SQHFBRQ/p1613590075008300) but we track NR events and not tessen events. I've also noticed (just from my own team) that if you're visiting a page briefly it's pretty easy to just ignore the box and never click it. You might want to look into making the cookie consent dialog box a bit more aggressive so that it's not in limbo at the bottom because users can fully use the page without choosing an option, meaning that they might not care either way. We can also look into instrumenting the cookie consent dialog box to see if it gets clicked!

**Comment by jpvajda** [comment]
Thanks @caylahamann this is all SUPER helpful. 🥂

**Comment by austin-schaefer** [comment]
Relates to #1331 for anonymous tracking info

**Comment by LizBaker** [comment]
Just wanted to chime in on what @tariqahmed was last seeing. 

I am able to trigger that Tessen event from the homepage on a fresh load but I accepted the cookie first. It's possible you said no to it at some point so you'll never trigger it, or maybe when you tried with that other page you happened to click accept?

You can test this out by checking the cookie in your `browser dev tools > application > cookies > newrelic-gdpr-consent`. If it's false then you'll want to delete it and accept the cookie banner that will appear. If it's true and you don't see Tessen fire-- that's interesting... and we can explore that. It hasn't failed for me throughout my exploration today. 

I can say with some certainty that the PageAction will always be a higher number as it tracks all signup click events via the browser agent while the Tessen event is only tracking folks who accepted the banner. Like Cayla said it's a very unobtrusive banner at the bottom so it's probably getting ignored. 

As far as the error Cayla came across goes that looks to be coming from the agent and not Tessen. Hopefully just a fluke as it continually reports. I haven't seen any come up as I've been poking at it today.

So, my conclusion is that PageAction is going to give you the true count of signup clicks while Tessen will give you the consented count. As far as GDPR goes I think as long as there isn't enough information to trace these events back to a specific person it's good to go. If we add authentication to these sites we'll have to rethink this tracking as it could include emails etc.

**Comment by jpvajda** [comment]
I've reached out to @tariqahmed  to see if he can review the findings above.

**Comment by tariqahmed** [comment]
@LizBaker 

Yup, set to true.

![image](https://user-images.githubusercontent.com/1187068/112364727-10cf4680-8c94-11eb-90d3-161b858df7b6.png)

**Comment by tariqahmed** [comment]
Hmm ok it appears to be working.... tested on multiple browsers, restarting fresh, etc...

So basically the difference between TessenAction and PageAction lets you derive how many people are basically not clicking on the consent. 

### Interesting Scenario:

What I did notice in retracing my steps - because the consent thing isn't blocking, and also innocuous, as a user you'll just go about using the site, potentially signing up... and so although you didn't say No, you didn't say Yes either... and the Tessen tracking doesn't kick in until you click on that Yes.

### Thoughts/suggestions:

- Instrument the Cookie  Consent dialog window so that we can track more authoritatively the choices users are making
- Run an Experiment in Split, and make the consent dialog a modal window that forces the user to make a decision, and see if that results in a higher Yes conversion rate.

@jpvajda @austin-schaefer

**Comment by jpvajda** [comment]
@tariqahmed  We have an issue for the instrumentation of the dialog here: #1507  And we'll consider moving the cookie dialog banner to be more pronounced after we instrument the dialog properly.  I don' think we need to run an experiment to determine the placement or if it needs to be more pronouced there are plenty of real world examples and articles on this topic, and if our goal is to get more users to click "accept" or at least click "deny" then making it more visible is a pretty easy decision.

As a note: we are also looking at enabling anonymous tracking in GA #1331 which will then allow us to track high level metrics, like sessions and page views for users that never click either button, or those that click deny. By doing this, then moving the cookie dialog banner around may just be unnecessary.
