### ISSUE TITLE
[Localization] Do not display the "Edit Page" button on non-english sites

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#1349]
We are not currently accepting PRs for the Japanese site or any other non-english sites in the future. We call this out in our PR template, but I think a better solution might be to just disable the button from the Japanese site.  By doing this, it will allow us to remove the Japanese sections from our PR template since we'd like to keep the template as short and simple as possible. We've already seen confusion because of how long the template is. 

We should be able to tell by the slug/path of the file whether this is an `i18n` file.

### Acceptance Criteria

- [x]  all non English site pages do not have the edit this page button visible. 
- [x] for pages that are machine translated this would also apply
- [x] Confirm design: should remaining button be centered / remain flexed?

### Location of button

**Footer**

<img width="1399" alt="Screen Shot 2021-06-10 at 2 30 07 PM" src="https://user-images.githubusercontent.com/1395158/121592904-82e43b80-c9f8-11eb-989c-b942f8a33275.png">

**Right Rail**

<img width="399" alt="Screen Shot 2021-06-10 at 2 29 58 PM" src="https://user-images.githubusercontent.com/1395158/121592909-84156880-c9f8-11eb-838a-80b0c71646d1.png">

**Comment by rudouglas** [comment]
This change needed to be done in the theme:

https://github.com/newrelic/gatsby-theme-newrelic/pull/582

**Comment by rudouglas** [comment]
Blocked: waiting on a theme release

**Comment by jpvajda** [comment]
@rudouglas what's delaying us from releasing the theme?

**Comment by nr-kkenney** [comment]
this issue is now blocked by: https://github.com/newrelic/gatsby-theme-newrelic/issues/590

aside from that, i took a quick peek with the current version of the theme and noticed the edit page is gone from the side bar section so thats 👍  but there is still an edit page on the footer, which i assume we also want to remove if its possible.

screenshots below
![Screen Shot 2021-11-23 at 4 19 25 PM](https://user-images.githubusercontent.com/70179215/143149236-cd0987c5-58e4-4686-9fd2-5f3f265b9476.png)
![Screen Shot 2021-11-23 at 4 19 39 PM](https://user-images.githubusercontent.com/70179215/143149275-89c7b7bf-578e-4221-8511-2d476e5d8612.png)

**Comment by rudouglas** [comment]
🤦 https://github.com/newrelic/gatsby-theme-newrelic/pull/592
