### ISSUE TITLE
Investigate site caching issues

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#1401]
In last couple weeks there have been times when a build check for a PR fails on Github, and forcing the gatsby cache to clean fixes it.

The two occurences included:
* in one image filenames were renamed and cleaning the cache fixed an error where old filenames were referenced somewhere in cache
* a release PR (develop to main) build check failed because of slug error re: our local plugin `gatsby-plugin-auto-index-pages`. cleaning the cache fixes it.
* data dictionary changes have caused the slug not found error and cleaning cache fixes it (presumably because of the `gatsby-source-data-dictionary`

It's not clear to tech docs folks when that cache may need to be cleared (nor when they see the error is it apparent). And it's not 100% clear to me either. 

Possible courses of action:
* Investigate and document what changes may require cache clean
* Determine if there's a better way to clean cache other than my hack of pushing a commit that makes trivial change to `gatsby-config.js`
* Look at the Gatsby performance flags we set in `gatsby-config.js` to see if those have any effect. Determine if we should / should not cache (though build times are almost an hour)

## Related info
https://github.com/gatsbyjs/gatsby/discussions/28331
https://github.com/newrelic/docs-website/pull/606
https://github.com/newrelic/docs-website/issues/1164

**Comment by jerelmiller** [comment]
Related https://github.com/newrelic/docs-website/issues/1164

**Comment by aswanson-nr** [comment]
Since we do not have a clear way to consistently reproduce this error, or any of the cache related errors. I recommend adding a 'retry' to the build that clears the cache and rebuilds if the original (that's using the cache) fails.
While it will increase build times when there is a cache error, it should still be less than having to go in and edit a file to invalidate the cache. There would also be significant slow downs for pipelines that fail for non-cache related reasons, since they will run the full build before giving up, this could be mitigated by looking for some type of string in the output before running again without the cache. However, I'm not sure what this string would be. @roadlittledawn @zstix Do you have any opinions on this?

**Comment by jpvajda** [comment]
The team will think through the approach here, prior to implementing another check to clear the cache.

**Comment by jpvajda** [comment]
We identified 2 options: 

`1` to put another check to clear the cache if a build check fails automatically  by adding a 'retry' to the build that clears the cache and rebuilds if the original (that's using the cache) fails

`2`. Do nothing an continue to support this on demand or instruct users to clear the cache if the build check fails.. Also we can reach out to the gatsby team on suggestions about this issue.

**Comment by jpvajda** [comment]
I'm thinking option `2` is the way to go right now.. if we all agree we can mark this done for now.
