### ISSUE TITLE
This is an enhancement request!

### ISSUE THREAD

**Issue by Actticus** [newrelic/docs-website#14178]
## Is your feature request related to a problem? Please describe

There is no way to change the displayed Docker hostname

## Describe the solution you'd like

Add the ability to change the displayed Docker hostname

## Describe why this important to you

There are several Docker hosts whose servers are named the same/not informative enough. So being able to change the display name for Docker would be a great idea

## Additional context

Nothing

**Comment by paperclypse** [comment]
You may be able to do this via custom attributes: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/#custom-attributes 

I'm closing this issue, because it's a product feature request. You should reach out to your account rep about this, if you have one.
