### ISSUE TITLE
Issue: 404 when trying to get info on data type `targetType`

### ISSUE THREAD

**Issue by glitchwizard** [newrelic/docs-website#14371]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

I'm looking for information on `targetType` from the `NrAuditEvent` data type. From this page: [NrAuditEvent](https://docs.newrelic.com/attribute-dictionary/?event=NrAuditEvent), there's a hyper link in the `actionIdentifier` attribute definition for [`targetType`](https://docs.newrelic.com/attribute-dictionary/nrauditevent/targettype)

When you click on this link, you get a 404 page, and that's where I pressed the button to 'create issue' for this issue. 

It gives some examples of `actionIdentifier` `targetType` values, but I'm looking for a comprehensive list of all the different values available. Is there one? If not could it be included in the docs, as well as a page specifically with more information on `targetType`

### Doc information (don't delete this section)

* https://docs.newrelic.com/404/
* **OS**: MacOS Ventura 13.5.1
* **Browser**: Firefox v116.0.3, buildID: 20230815173142
* **Device**: Macbook Pro

**Comment by rhetoric101** [comment]
@glitchwizard thanks for the heads-up about this broken link. Our developers are working on a fix for that.

You may have already just searched in the data dictionary for just `targetType`. It has a [brief explanation](https://docs.newrelic.com/attribute-dictionary/?attributeSearch=targetType). It sounds like you want an exact list of `targetType` instead of just a general list like this: account, role, user, alert conditions or notifications, logs, etc. Is that correct?

**Comment by rhetoric101** [comment]
@glitchwizard here's what I'm going to try to insert in the docs:

To generate a list of `targetType` values, run the query below. Note that this query will only show `targetTypes` that have been touched.

FROM NrAuditEvent
SELECT uniques(targetType)
SINCE 90 days ago
