### ISSUE TITLE
Issue: Introduction to Plugin Central

### ISSUE THREAD

**Issue by philweber** [newrelic/docs-website#1485]
The instructions on this page to access Plugin Central are not accurate: _Plugins_ is no longer an option under the _More_ menu.

**Comment by barbnewrelic** [comment]
@philweber  Last year when Plugins EOL was announced, the PM and I intentionally decided we were not going to update Plugins docs other than to add info about the EOL. Months ago the https://docs.newrelic.com/docs/plugins/plugins-new-relic/get-started/introduction-plugin-central/#eol-plugins section was added to the top of each Plugins doc. That section points to two Explorers Hub posts, https://discuss.newrelic.com/t/first-notice-limiting-access-to-new-relic-plugins/121832 and https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267 , which explain you no longer have access. We also intentionally limited findability of Plugins docs on the Docs site itself, because the vast majority of New Relic customers should be using integrations or developer.newrelic.com for a much better experience.

We do not plan to update Plugins docs further until closer to official EOL in June, because we want any remaining customers who use plugins to communicate via those Explorers Hub posts or their account rep on how to migrate away from plugins. The Explorers Hub posts are a much better way for New Relic to understand the remaining user experience before official EOL. I hope this helps clarify!

**Comment by mmfred** [comment]
Thanks @barbnewrelic and @philweber - I'm going to close as "by design."
