### ISSUE TITLE
Issue: We've lost the NerdGraph section in nav

### ISSUE THREAD

**Issue by urbiz-nr** [newrelic/docs-website#1516]
Looks like we've lost the NerdGraph category nav during migration, the docs are there but as stand-alone. For example:

- https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph
- https://docs.newrelic.com/docs/apis/nerdgraph/examples/create-widgets-dashboards-api
- https://docs.newrelic.com/docs/apis/nerdgraph/examples/export-dashboards-pdfpng-using-api/

See screenshot for what's missing.

<img width="214" alt="Nerdgraph nav" src="https://user-images.githubusercontent.com/43602284/112271401-2be18c80-8c7b-11eb-9961-2c780e9e8f2b.png">

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/examples/export-dashboards-pdfpng-using-api/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by jpvajda** [comment]
@roadlittledawn checking to see if we resolved this issue as I saw some chatter on it in hero channel

**Comment by roadlittledawn** [comment]
yeah it seems during migration the nav .yml files weren't updated to include most nerdgraph docs. so the fix is to add those links to the nav .yml and left nav will populate. i think TDP is the nav they likely need to live.

the only nerdgraph doc that did make it in was https://docs.newrelic.com/docs/apis/nerdgraph/tutorials/provisions-your-subscriptions-nerdgraph in `new-relic-partnerships.yml`
