### ISSUE TITLE
Automatically keep private repo in sync with public repository

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#1686]
## Description
Once we have created a private repository in our Github environment (#1063 via #1685), we need a way to keep it in sync with the public repository. 

After discussing it, we have decided to create a Github action that will PR the private repository at regular intervals with content from the public repository.

## Acceptance Criteria
* [x] Create new action to keep code in sync.
* [x] Set up action to run on cron schedule.
* [x] Update Documentation for Docs Writers (_in Google Drive_)

**Comment by nr-kkenney** [comment]
updated the ticket to reflect using public github.

**Comment by nr-kkenney** [comment]
for the action's implementation, i think we only need to sync develop & main (versus every single branch), since those are the long living branches from the public repo.

i also think the action can just merge the remote branches & push that up directly. this should always be fast forward merge w/ no conflicts, since no one should push to develop / main within the private repo.

if we want to push for some standardized naming of branches, we might also be able to automatically sync the branches writers are working on (with changes from public develop, etc), but I think this is a stretch goal.

**Comment by nr-kkenney** [comment]
calling this done.
