### ISSUE TITLE
Investigate build errors caused by the cache

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/docs-website#1751]
### Description
Builds are failing, apparently randomly, due to an error thrown by our local plugins. This error can be worked around by adding a commit that invalidates the cache and building from scratch.

Examples of this error:
* https://github.com/newrelic/docs-website/runs/2255367377?check_suite_focus=true
* https://github.com/newrelic/docs-website/pull/1595/checks?check_run_id=2255435454
* https://github.com/newrelic/docs-website/pull/1666/checks?check_run_id=2255574521
* https://github.com/newrelic/docs-website/pull/1694/checks?check_run_id=2279444762

From those examples, we see that error appears to center around the `gatsby-auto-index-pages` plugin. Specifically, when the `generate-html` function is run on an image. (You can see the node the function is operating on printed out before the error)

**Comment by nr-kkenney** [comment]
@jpvajda @aswanson-nr 

@roadlittledawn had a great idea for at least easing the process around this, if we can't resolve the core issue.

To paraphrase -- and Clinton feel free to edit / correct if I misrepresent the idea 🙈 :

instead of adding a commit as needed / when we requested, we create something like a new workflow which clears the cache whenever someone leaves keywords in a pr comment. I imagine this would be something like "clear cache", but hopefully the idea overall is clear.

I think this would be worth implementing in the event that we cannot resolve the core issue, in this ticket, or maybe just a separate one.

**Comment by jpvajda** [comment]
Interesting @roadlittledawn I had an idea to:

add a script to they package.json file to standardize on how to clean the cache, stop services, etc.  something like `yarn docs full clean`

also an idea from @rhetoric101 .....

similar to the script concept where we provide easy yarn commands to do the following locally:

```
Press 1 for light clean:
    *yarn
    *yarn clean
    *yarn start
Press 2 for a heavy scrub
    *rm -rf .cache
    *yarn
    *yarn clean
    *yarn start
Press 3 for a full pressure wash
    *rm -rf .cache
    *rm -rf node_modules
    *yarn
    *yarn clean
    *npm rebuild --verbose sharp
    *yarn start
```

**Comment by nr-kkenney** [comment]
if this is a new separate workflow from the build, we have to "clear" the git cache rather than the gatsby cache. 

however, there is currently no way to delete entries from the git cache, so I think what we want to do is create a new valid cache entry that will allow the next site build run to succeed. 

i was originally thinking we could just create an empty cache entry so the site rebuilds from scratch, but we dont want to cache that since every subsequent build will do a full build until that cache entry expires.

**Comment by jpvajda** [comment]
This could be another one we save for our Gatsby build audit, to get their perpective on how to proceed. @zstix what do you think?

**Comment by jpvajda** [comment]
This may be resolved with our Gatsby V3 upgrade...

**Comment by jpvajda** [comment]
It sounds like this is still occurring after v3 upgrade, as @dbarnesbrownNR reported seeing this error on `5/6/21`

**Comment by jpvajda** [comment]
And one more consideration from @aswanson-nr  

According to what I’m seeing on Github, the last develop->main merge to fail on a cache error was last month! https://github.com/newrelic/docs-website/actions/runs/712290063
That being said, I think we should still keep an eye out just in case.

**Comment by jpvajda** [comment]
after further investigation:  We feel it's closed and can re-open if it comes up again. 🚀
