### ISSUE TITLE
Referrer URL is not passing with the `TLMK_Signup_Signup` event

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1816]
###  Related

We thought this change should fix this problem, but after testing it, it's still not working

https://github.com/newrelic/gatsby-theme-newrelic/issues/342

### Step to reproduce 

1. go to docs.newrelic.com
2. click on free account
3. using the [segment chrome extension](https://chrome.google.com/webstore/detail/segment-event-tracker/hbanigoffkilibdakdmmlgefndpjmajl?hl=en) view the `TLMK_Signup_Signup` event
4. the referrer url should be present

### Acceptance Criteria

- [ ] The Referrer URL is present in the `TLMK_Signup_Signup` event.
- [ ] This URL is visible in Segment
- [ ] Zoe confirms this issue is resolved through the analytics pipeline.
- [ ] Upgrade theme for docs, opensource, developer site.

<img width="736" alt="Screen Shot 2021-04-13 at 5 27 08 PM" src="https://user-images.githubusercontent.com/1395158/114633376-a2234e80-9c7d-11eb-95cb-858cf70e49cf.png">

<img width="537" alt="Screen Shot 2021-04-13 at 4 01 06 PM" src="https://user-images.githubusercontent.com/1395158/114632987-faa61c00-9c7c-11eb-8560-826252e7cba3.png">

**Comment by jpvajda** [comment]
This wasn't fixed by  removing the utm param from the signup button click so moving back in todo

**Comment by aswanson-nr** [comment]
Okay, @LizBaker and I were able to figure out what's happening. The `referrer` field was not being sent when a user clicks the `free account` button on our sites. This was caused by the `rel="noreferrer"` property on our the SignUpLink component.
The `noreferrer` and `noopener` types control the information passed to the new tab. The former prevents referrer information from being passed to the new tab and the latter prevents the new tab from accessing `window.opener`.
The `noopener` type is sufficient to protect the user from any malicious code, but it is not implemented in some [older browsers](https://caniuse.com/rel-noopener).

We have 2 main options to fix this:
1. Remove the `noreferrer` type and stick with just `noopener`
2. Link directly to the signup page instead of opening it in a new tab

References:
* https://html.spec.whatwg.org/multipage/links.html#link-type-noopener
* https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types
* https://caniuse.com/rel-noopener

**Comment by jpvajda** [comment]
I like `1`  🥳

**Comment by LizBaker** [comment]
checked with security juuuust in case and we have the green light for `noopener` only

**Comment by jpvajda** [comment]
I asked Zoe for input here as well. 🆘

**Comment by jpvajda** [comment]
Let's go with option `1` for the win here. @aswanson-nr 🥇

**Comment by nr-kkenney** [comment]
published a release for the theme so now its 2.0.1. i pushed a branch for the theme upgrade in opensource and docs, but was waiting for other changes in developer to go through. so those can be picked up.
