### ISSUE TITLE
Figure out how branch protection was turned off for the docs repo

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1827]
IT seems some how branch protection was disabled for `develop` and `main` branches and we aren't sure why.

### Acceptance Criteria

- [x] Turn back on branch protection for develop and main
- [ ] Determine a root cause of what occured
- [ ] document our branch protection rules in the [contributing guide](https://github.com/newrelic/docs-website/blob/develop/CONTRIBUTING.md) so we can remember what we set 😄 and can communicate that to contributors

**Comment by zstix** [comment]
@jpvajda I don't believe there is a way to get a log for repository setting history. It looks like there is a way to get an [audit log](https://docs.github.com/en/rest/reference/orgs#get-the-audit-log-for-an-organization) for the organization, but I don't think it would include the information we're looking for (and I don't think I have sufficient permissions).

My best guess is that this was caused by an action that broke mid-run, but I haven't found any actions that are in that state. I'm not really sure what other steps we can take to determine the root cause.

I'll update the contribution guide today.
