### ISSUE TITLE
Duration definition is wrong

### ISSUE THREAD

**Issue by jpenna** [newrelic/docs-website#1855]
The `duration` definition has the same description as `accoutnId`
https://docs.newrelic.com/attribute-dictionary/?event=Transaction

**Comment by rhetoric101** [comment]
@jpenna, when I look at the [attribute dictionary](https://docs.newrelic.com/attribute-dictionary/?event=Transaction), I see two different entries:

accountID: The unique ID of the account associated with the service/application where the Transaction was created.
duration: The total server-side response time for the transaction, in seconds. Does not include request queueing time.

Perhaps you could attach a screen capture showing the issue.

**Comment by jpenna** [comment]
Interesting! I see the same as you when I open the link, but when I navigate from the tool-tip, I land in this error, and when I click the Transaction link, it keeps showing me the wrong description in the list.

Hope the screenshots will help:
![tooltip](https://user-images.githubusercontent.com/16005946/115051520-49d59200-9eb3-11eb-8ae2-42271c18c0df.png)
![desc](https://user-images.githubusercontent.com/16005946/115051508-46daa180-9eb3-11eb-80c9-35129eaadc32.png)
![list](https://user-images.githubusercontent.com/16005946/115051514-493cfb80-9eb3-11eb-9ad8-85855360b9c2.png)

**Comment by jpenna** [comment]
Just so you see I see the correct description if I click the link directly:

![Screen Shot 2021-04-16 at 12 58 16 PM](https://user-images.githubusercontent.com/16005946/115051706-7f7a7b00-9eb3-11eb-93a9-b00bd2b89a12.png)

**Comment by zstix** [comment]
Thanks for finding this issue! It looks like the attribute dictionary is always returning the _first_ description for a data type, but only when you go to the page directly (as opposed to applying a filter).

[Here is another example](https://docs.newrelic.com/attribute-dictionary/?event=ContainerSample&attribute=cpuKernelPercent) - We should see the description for `cpuKernelPercent`, but it's showing the description for `commandLine` because that's the first description in the `ContainerSample` data type.

**Comment by zstix** [comment]
Turns out we already have an issue filed for this! #1670 

I'm going to close this one out, since it's a duplicate. Thanks again for finding and reporting it!
