### ISSUE TITLE
ES module loader uses discouraged experimental flag

### ISSUE THREAD

**Issue by Duske** [newrelic/docs-website#18840]
## How can we make our docs better?
In https://github.com/newrelic/docs-website/blob/develop/src/content/docs/apm/agents/nodejs-agent/installation-configuration/es-modules.mdx it suggests using the experimental-loader. 
![image](https://github.com/user-attachments/assets/304c28b4-f6eb-462f-baa1-bfbe7d8b569b)
According to node.js docs, this flag is now discouraged:
> This flag is discouraged and may be removed in a future version of Node.js. Please use --import with register() instead.
https://nodejs.org/api/cli.html#--experimental-loadermodule

What is the proper way to register newrelic module with the import API?

**Comment by rhetoric101** [comment]
@Duske I discussed your question with our developers, and here's what they said: "The New Relic Node.js agent continues to require the use of the `--experimental-loader` flag in order to instrument ES Modules. The flag has not been removed from Node core, and our agent will update accordingly in due time."
