### ISSUE TITLE
Issue: Right nav is grouping certain headers that should be separate

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#1953]
### Tell us what you need

If you navigate to: https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/alert-custom-violation-descriptions/#create-description-nrql, you can see the following:

![Screen Shot 2021-04-21 at 4 11 45 PM](https://user-images.githubusercontent.com/70179215/115632406-7ecf5380-a2bc-11eb-968a-686fa1222f1b.png)

The highlighted "section" should be two separate sections, but are grouped together. If you click on the section, you are navigated to the top link (and are unable to navigate to the bottom link from the right nav).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/alert-custom-violation-descriptions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rudouglas** [comment]
Digging into this it seems like both links were being rendered with the same `href`...

```
<li class="css-ti75j2">
<a href="#create-description-nrql" class="active css-1himwak">Create a custom violation description with NRQL</a></li>
<li class="css-ti75j2">
<a href="#create-description-nrql" class="active css-1himwak">Mentioning users or notifying channel in Slack</a></li>
```

...caused by the same `href` tag used in the [markdown page](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/alert-custom-violation-descriptions.mdx).

The PR #2112 should fix this instance but @nr-kkenney i'm wondering if you saw any other examples of this?
