### ISSUE TITLE
Feedback: Introduction to account settings

### ISSUE THREAD

**Issue by markroeser** [newrelic/docs-website#1954]
### Tell us more about your feedback

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc? 

link to actual functionality. Every link seems to be circular here.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/general-account-settings/introduction-account-settings/
* **OS**: Mac OS 10.14.6
* **Browser**: Chrome 89.0.4389.114
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@markroeser Thanks for feedback. Our account settings docs are definitely a thorny area, because we have two different account/user models possible, which makes things a bit confusing. This will hopefully not too much longer be the case as we align on one user model. If you have time, can you be a little more specific about what you were trying to get to and what you couldn't find? That might help us understand where things are getting most confused.

**Comment by zuluecho9** [comment]
Going to close this. We do have a number of issues in accounts docs, with our two user models complicating things. I have a number of projects coming to improve this area, and then we'll be moving to a single user model towards end of year, which will help us simplify things.
