### ISSUE TITLE
Issue: WordPress specific functionality

### ISSUE THREAD

**Issue by MartinGF** [newrelic/docs-website#1962]
### Tell us what you need

In this document you recommend a plugin that has not been updated in 2 years.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/php-agent/frameworks-libraries/wordpress-specific-functionality/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Thank you much @MartinGF. We had some work for this in the backlog and your issue has helped us prioritize this. Thank you.

**Comment by austin-schaefer** [comment]
Reopening this issue until the related Jira ticket is closed

**Comment by bradleycamacho** [comment]
@zuluecho9 Looks like the corresponding jira was closed. Can you re-triage this issue and figure out the next steps and/or if we should close it?

**Comment by barbnewrelic** [comment]
As of 12-01-2021 there's a WordPress quickstart doc in development that **also** refers to our browser monitoring plugin for WordPress. See DOC-7563.

WordPress website https://wordpress.org/plugins/rt-newrelic-browser/ has a disclaimer "This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress."

I've asked our PHP experts whether we should simply delete the reference to the browser plugin as a short-term bandaid. But I agree with @zuluecho9  that the doc itself needs to be prioritized. It hasn't been updated literally in years. Not sure what drove the decision to close DOC-6603.

**Comment by barbnewrelic** [comment]
I suspect there are very few people here who know the backstory behind that browser plugin referenced in our doc, and that's why I haven't been able to find an engineering team to confirm. I was here when that plugin was originally released, so I have taken the liberty to delete the reference to it in our doc. See conversation in slack channel 12-07-21. I think the doc update in https://github.com/newrelic/docs-website/pull/5205 can close this issue.
