### ISSUE TITLE
Remove duplicate files to decrease overall size of the Site

### ISSUE THREAD

**Issue by rudouglas** [newrelic/docs-website#2182]
I wrote a Python script that hashes each file in the Repo and checks for duplicate content. The file-names may be different but using the hash the content could be identical. The results were the following:

Preliminary tests on Docs Site:

- Duplicate Count:  403
- Total Size:  457.39 MB
- Duplicate Size:  48.68 MB
- % Saved:  10.642656729322791

You can see an example of the script running in a GitHub Workflow in my [forked Repo here](https://github.com/rudouglas/github-actions/runs/2519612107?check_suite_focus=true#step:4:1000)
Most of these files are images so it would make more sense to only have a single copy of each.

It outputs the path that each duplicate is found at to make it easier to review. What we need to talk about is 

- [ ] The advantage to fixing this with regard to the Site build time etc.
- [ ] The Eng work that would be required and if that's worth it

Preliminary tests on Developer Site:

- Duplicate Count:  93
- Total Size:  301.46 MB
- Duplicate Size:  8.5 MB
- % Saved:  2.819673832597146

Preliminary tests on OSS:

- Duplicate Count:  15
- Total Size:  69.12 MB
- Duplicate Size:  892.05 KB
- % Saved:  1.2603888143788724

**Comment by roadlittledawn** [comment]
awesome! definitely nice to see this quantified.

one bit of context re: images in docs-website repo. we chose to add `images` sub-directories in same dir as the file referencing the image to make it easier for content contributors to reference the image path. that comes with the expense of needing to create separate files for the same image when referenced in other files in other directories. 

but there are quite a few instances of the same image being created multiple times because it's used in multiple files across the site. my sense is at some point we probably want to reduce those multiple copies and stick all images in one directory, at the expense of longer, not-as-easy-to-quickly-understand image paths.

**Comment by jpvajda** [comment]
@roadlittledawn great context here.  from what I understand the work to move to a single image directory would be a decent amount of effort, and it's not clear it's worth doing all of that eng work and introducing an new image workflow to the Docs Team, if I understand these numbers correctly:

```
    Duplicate Count: 403
    Total Size: 457.39 MB
    Duplicate Size: 48.68 MB
    % Saved: 10.642656729322791
```

We'd only yield a decrease in overall size of 48.68MB? If so, that doesn't seem significant enough to invest time in a different approach. but I'm happy to discuss further @rudouglas .

Perhaps we should be periodically checking these duplicates, as at some point, it may make sense to address it.

**Comment by jpvajda** [comment]
@rudouglas Do you think you could evaluate how much this may increase overall build time? It may be better to try to do that once move to Gatsby Cloud, so we understand the impacts on the new platform vs. the old.

**Comment by jpvajda** [comment]
@nr-kkenney totally. I think it be interesting to revisit this `when / if` we move to gastby cloud and `when` we onboard another country. so i'll reopen and tag it under localization.

**Comment by roadlittledawn** [comment]
@rudouglas any chance you can run that script again on repo nowadays to see how many dupes we have?
