### ISSUE TITLE
Disabling all 🍪 cookies breaks site components 

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2293]
Relates to: 

#2287 

Disabling all cookies effects components in odd ways, like collapsers & landing page tiles & navigation, & the data dictionary page.

`note` given this was found with #2287 it may be related to the free account button not rendering when cookies are disabled.

Steps to repro:
* Disable all cookies
* Navigate to a page with a collasper  or a landing page tile, or try to use navigation arrows to expand / collapse nav, or just go to the [data dictionary page](https://docs.newrelic.com/attribute-dictionary/)
* Observe the odd behavior

![Screen Shot 2021-05-13 at 3 29 33 PM](https://user-images.githubusercontent.com/1395158/118198796-d4f06c00-b40e-11eb-8636-4f68f374f778.png)

### Acceptance Criteria
- [x] Collaspers appear correctly in browsers with cookies disabled 
- [x] landing page tiles appear correctly in browsers with cookies disabled.
- [x] Nav arrows work correctly
- [x] Data Dictionary page renders correctly

**Comment by jpvajda** [comment]
We discussed timeboxing this to see if there is a quick resolution but browsers do make it clear that by disabling all cookies you may break website functionality.

**Comment by LizBaker** [comment]
I played around with this a bit in the theme and it seems react-spring (our animation library) doesn't function when cookies are disabled, so any component with any kind of animation will break

**Comment by jpvajda** [comment]
@LizBaker interesting finding.. I wonder if there is anything we can report to React-Spring? perhaps file an issue? https://github.com/pmndrs/react-spring/issues?q=is%3Aissue+is%3Aopen+

**Comment by aswanson-nr** [comment]
This appears to be caused by interacting with the localStorage API. When all cookies are disabled, that API throws an error when we try to set a new item and appears to completely throw us out of the JS execution in the browser. I'm further convinced that this is the root cause because a lack of JS would make the site operate in the way we are seeing. If no JS is running, then the collapsers wouldn't open, the nav wouldn't work properly, the search wouldn't work, etc. 

Using Safari with all cookies blocked I ran into this error, along with a few other similar ones.
<img width="708" alt="Screen Shot 2021-05-19 at 4 03 19 PM" src="https://user-images.githubusercontent.com/70179303/118895823-c2b57880-b8bb-11eb-9446-1eeb0e99f9ef.png">
After digging deeper into this error, I noticed that it appears to be coming from some code around setting the light/dark theme.
<img width="911" alt="Screen Shot 2021-05-19 at 4 04 10 PM" src="https://user-images.githubusercontent.com/70179303/118895942-fd1f1580-b8bb-11eb-83ee-ff8c642df005.png">
This code appears to be coming from the `use-dark-mode` npm package.

I didn't see a quick fix, so I didn't dig any deeper besides checking to see if the package had anything about this use case in its documentation (it doesn't). If this is the root cause of this issue, then we will need to file an issue with the `use-dark-mode` package or move to handling the theme mode internally.

**Comment by jpvajda** [comment]
@aswanson-nr that's a good assessment! Maybe we discuss in Standup parking lot?

**Comment by aswanson-nr** [comment]
@LizBaker and @jpvajda, I went through the theme and disabled all uses of the `use-persisted-state` library and I was able to get the demo site running!
The library does not seem to be able to handle the case where users have disabled all cookies. It should be possible for us to keep the majority of the site operating normally by replacing the `use-persisted-state` library with another one that will fallback to an in-memory store if localstorage isn't available. This is also something we could consider implementing ourselves, since the API is very simple.

**Comment by aswanson-nr** [comment]
This library, [use-local-storage-state](https://www.npmjs.com/package/use-local-storage-state), looks like a great candidate to replace `use-persisted-state`. There's even a section on handling edge cases when localstorage isn't available, https://www.npmjs.com/package/use-local-storage-state#is-persistent-example.

**Comment by jpvajda** [comment]
Nice!

**Comment by aswanson-nr** [comment]
Proposed AC:
* Update all uses of `use-persisted-state` to use `use-local-storage-state`
* Update the `useUserId` hook to use `use-local-storage-state`
* Add a banner when cookies are disabled

**Comment by jpvajda** [comment]
@aswanson-nr curious why this is blocked? Did we decide to just punt on this for now, and focus on getting the free account to render without cookies being enabled?

**Comment by aswanson-nr** [comment]
@jpvajda Exactly that! I wanted to talk through that decision in standup

**Comment by aswanson-nr** [comment]
Deep dive:
Local storage is used 4 places in the theme
1. user id storage
    * Currently uses a custom implementation with local storage
2. the `use-dark-mode` library
    * uses the `use-persisted-state` library under the hood, this library does not work well when cookies are disabled.
    * the default storage provider can be overridden to use an in-memory store.
3. `on-client-entry` to check if dark mode is used (seems to just exist for reporting)
    * adding a try/catch block around the local storage calls allows the client to continue working fine when cookies are disabled.
4. the announcement banner
    * currently uses `use-persisted-state`

Proposed changes:
1. Update this to use the `use-local-storage-state`.
2. Check to see if local storage is available, then pass in an in-memory store if it isn't.
3. Add the try catch around access local storage.
    * What should the NR custom attribute default to?
4. Update this to use the `use-local-storage-state`.

I'm going to submit a PR for these changes, since I basically made all these changes during testing.
