### ISSUE TITLE
Issue: Amazon EC2 monitoring integration

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#2415]
A few days ago, on a host with EC2 integration enabled.
The displayName appears to have changed from hostname to entityName.

Do you have any guidance on this?

**Comment by rhetoric101** [comment]
@qryuu, sorry for our late response, but our engineering teams have noticed this issue and are trying to understand it. I don't think that this will change the documentation since it may be a bug. To track the progress on this issue, I recommend that you contact Support or look at the Explorers Hub (https://discuss.newrelic.com/).
