### ISSUE TITLE
Issue: Networks

### ISSUE THREAD

**Issue by ruffy91** [newrelic/docs-website#2416]
### Tell us what you need

- Some endpoints are missing, more specific:
- The install.sh script also needs access to GitHub
- The API URLs api.eu.newrelic.com and api.newrelic.com are not mentioned explicitly

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/networks/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by mmfred** [comment]
Hi @ruffy91 - thanks so much for taking the time to drop us some feedback. We took a look at your input. A follow-up question for you:

- We did not include the GitHub info on this Network page or the more relevant page, which is [here](https://docs.newrelic.com/docs/full-stack-observability/observe-everything/get-started/new-relic-guided-install-overview/#ohi-recipes), because in most cases, unless you are using the CLI to install integrations, you won't interact with GitHub. However, can you let us know if you hit a bump on that?

Thanks! 
The Docs Team
