### ISSUE TITLE
Issue: Compatibility and requirements for the Java agent

### ISSUE THREAD

**Issue by mb-newrelic** [newrelic/docs-website#2420]
I wonder if the title of this doc is doing enough to let users know that the doc includes so much about everything that's automatically instrumented. I can imagine users miss some pretty critical info here.

Part of the issue may also be that the default setting hides the frameworks and libraries.

Thoughts? Thanks!

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/java-agent/getting-started/compatibility-requirements-java-agent/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@mb-newrelic, thanks for your input on this. I discussed this heading with some Java developers and they prefer to keep the main heading as it is since it covers both requirements and compatibility. I hope this isn't a continued source of confusion for customers. 

On another note, I noticed that the sub-heading "Automatically instrumented frameworks and libraries" includes the same phrase as the child collapser "Frameworks and libraries." I discussed this with engineers, and they are OK with this change of the heading:

OLD: Automatically instrumented frameworks and libraries
NEW: Built-in instrumentation

I hope this helps. We are making this small change in PR #2506.
