### ISSUE TITLE
[Localization] Workflow submits already translated files for translation

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#2454]
## Description

@jmiraNR reported we may be erroneously submitting files in `src/i18n/content/jp` for translation, when we should only be sending English files in `src/content` that have a `translate` field in their frontmatter.

Julian cited [this recent job](https://dashboard.smartling.com/app/projects/bf1be2489/account-jobs/bf1be2489:kqjsfpadl3km/files), and I can see we definitely have files with the `i18n` path. Need to investigate further to determine why / if we should be excluding those and if we write them back correctly when we create a PR.

## Expected behavior
Only submit English files in `src/content` marked for translation via their frontmatter to translation vendor. When complete and we create PR, ensure we write back to relevant path in `src/i18n/content`

### Acceptance Criteria

- [ ] Get Team access to Smartling (kris, liz, Alec, Ruairi) - @jpvajda 
- [ ] Filter out any markdown files that are a non-english language type.
- [ ] Don't add any translated file to the the translation queue

**Comment by LizBaker** [comment]
Our workflow doesn't strip out the `translate: - jp` frontmatter in translated docs when it PRs new/changed files. This is why we suddenly had some japanese files get grabbed for translation, since we check for that frontmatter. I'll be looking into how to strip that out when deserializing, which should solve the issue (along with manually editing the 15 files which gained that frontmatter)
