### ISSUE TITLE
New search not finding things in a pretty essential way

### ISSUE THREAD

**Issue by mmfred** [newrelic/docs-website#2455]
Examples reported in the documentation channel:

- Searching for ‘Aggregation window’ is not populating anything in the live search dropdown regarding Alerts but there are several pages I can think of that should be there. Namely [Advanced signal settings](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions/#advanced-signal).
- Searching on 'derivative' yields no results. 
Found it here: https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#derivative ( first checked under math functions, then found it under regular functions)

@jerelmiller - Austin asked me to tag you on this.

**Comment by jerelmiller** [comment]
That is interesting. One minor change we made was to weight the title field a bit more than anything else. Perhaps it isn't searching the body correctly?

When weighting the fields, we weight the `title` 2x more than anything else and use a wildcard to try and get it to match all other properties. Our search weights look like the following ([source](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/SearchModal/search.js#L27-L29)):

```js
search_fields: {
  page: ['title^2', '*']
}
```

According to a help ticket I filed back with Swiftype in August, they recommended that I use the `*` to search across all properties. I'm wondering if maybe the search is not including the body because its not specified in that list (in which case, the `*` is a lie 😞 ). 

A quick suggestion would be to try adding `body` to that array and see if that fixes the issue.

**Comment by jerelmiller** [comment]
For reference, here is the text of the email I received:

--- 

Hi there,

Thanks for reaching out to us. Before I answer your question, is your main concern searching fields through a curl or through your web site? If it's the website we can apply weights to fields as described in the link below

Here is more information:

https://swiftype.com/documentation/site-search/guides/weights

If your main concern is through a curl, please give 


For example:
 
curl -X GET 'https://search-api.swiftype.com/api/v1/public/engines/search.json' \

  -H 'Content-Type: application/json' \

  -d '{

        "engine_key": "YOUR_ENGINE_KEY",

        "q": "brothers",

        "search_fields":{

          "books":["title^3”,”*”]

        }

      }'

Please try using an asterisk. I think that should work. Please let me know if the results.

**Comment by HenryTech** [comment]
Searching for "Evaluation offset" does not lead to the NRQL alert condition creation docs on that subject, but instead leads to a doc on ... funnel queries.

**Comment by austin-schaefer** [comment]
A Relic reported these in #documentation as other examples of fairly common searches with expected results that aren't showing up at all:

* https://docs.newrelic.com/?q=desc
* https://docs.newrelic.com/?q=csv

**Comment by jerelmiller** [comment]
I'm fairly confident that Swiftype is not honoring the wildcard (`*`) so it's not actually searching against the body text, just the title. An easy fix should be to update that `search_fields` field to include `body` and see if that fixes things.

**Comment by jpvajda** [comment]
@zstix  FYI on this one, it seems a PR has been submitted for the fix so I added to to `in review`
