### ISSUE TITLE
# in SQL Password

### ISSUE THREAD

**Issue by MasterAce** [newrelic/docs-website#2504]
You may want to add into your documentation not to use the # in your SQL password. Also is there is any other characters you should not use. It may help someone else save some time.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@MasterAce, thanks for the heads-up about this. I'm checking with our engineers about password limitations.

**Comment by rhetoric101** [comment]
@MasterAce, it turns out there was a bug that was corrected in February. You can see the release notes here: https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1152/

So, we no longer have forbidden literals in passwords. If you are still having trouble with this, perhaps you are using an older infrastructure agent.
