### ISSUE TITLE
[Machine Translation] Add disclaimer for machine translated pages

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#2537]
<details>
  <summary>❓ Design questions</summary>
  
- [x] what is the language we use for this disclaimer?

> language should be in the localized language of the translated site, JP etc. 
> terminology will be confirmed by UX-writing team

- [x] where does this disclaimer get placed on page?

> in the top of the right rail.

- [x] What is the feedback capture mechanism we'd use to get feedback if the page translation is good or not?

>  see recommendation to use a callout banner

- [x] Can we reuse the section for `edit this page`, as it's not going to be displayed on the all translated pages. 

> It's not recommended by UX  see below.

- [x] Can we ask this question on all translated pages? if it has an issue. 
 > just MT pages only

- [x] Are 👍 👎 ok for Japanese users? 

> We should consider removing the thumbs up/down in the feedback bar. Please see example for [meaning of thumbs](https://japanyugen.com/thumbs-up-japan-meaning-of-hand-gestures-in-japan/) down in Japanese: . I suggest we use `Yes / No.`
</details>

><!> Please use the https://github.com/newrelic/docs-website/tree/feature/machine-translation feature branch

----
### Background
Since machine translation isn't perfect, we want to add a disclaimer for any page that has been machine translated to let the user know and to invite them to leave any feedback about it

The mechanism for knowing if a page has been machine translated is implemented in #2536.

### Content to use 

relates to `JIRA` `UIWRITE-1411`

**Right rail Header**

Is this a good translation? `Yes`  `No`

**Body**

We used machine translation for this page. If there’s anything unclear, you can try checking the English version. Or tell us how we can improve it.

In the frontmatter this will look like:

```
translationType: machine
```

### Design quetions
- What buttons / disclaimer should be used? 

### Acceptance Criteria
- [x] Disclaimer is added to any machine translated page on the site via a call out banner
- [x] It would be best if these info/disclaimer messages were translated by humans into our localized languages
- [x] Add tessen instrumentation for calls to action in disclaimer
- [x] Display translated disclaimer messages

Relates to: #2341

### Mock Up
This is the final Copy:

![image](https://user-images.githubusercontent.com/3636549/140736536-1d17edd9-7cac-4986-b60a-d429baf97e77.png)

Figma: https://www.figma.com/file/0jsTPLtwz6Bljndkbr1COn/?node-id=132%3A42586

**Comment by nr-kkenney** [comment]
i had originally thought this would occur when the site builds, but it was pointed out that the disclaimer should match the locale of the page -- if the page is in japanese, the disclaimer should be in japanese -- so this will need to occur as part of the translation github workflows, rather than when we build / deploy the site.

**Comment by jpvajda** [comment]
Not sure of the design status on this one, so I can bring it up with @legnaleama for direction.

**Comment by jpvajda** [comment]
@jpvajda will follow up in this...

**Comment by jpvajda** [comment]
I've made a crude mock, and asked #ui-writing for their input here and share this with @legnaleama for design input

**Comment by legnaleama** [comment]
I have some questions and concerns related to the requirements and approach:

- We are trying to define the best text in English to be translated into Japanese, correct?  Meaning, (for now) this experience will only be visible/available to our Japanese audience. @jpvajda 
- If we are planning on re-using the top section of the right sidebar for 2 different actions depending on weather or not the page has been translated by a machine, we could end up confusing our users if there's a chance any of the pages has been translated by a human and they happen to explore both. I'd say it's impossible to measure the probability of that happening but for the sake of consistency and coherence I don't think we should approach it this way.

With those considerations in mind, my proposal is to use a callout banner. I noticed there is already a callout on the code named `caution.js` but I don't know how to preview it's render so I went ahead and created a new component.

*Notes*
- I added a Japanese version for the sake of realism but it would be good to run that by a native speaker, my jp is a mix of google translate and what I can remember from when I tried learning it ages ago [😅]
- I also made a mockup with the new navbar we've been working with Docs just to check vertical spacing when we migrate to the new one.
- The mobile version only contains the question to reduce vertical noise but since this isn't sticky we could also add the MT disclaimer if we need to.
- The callout CAN NOT be dismissed. This is not sticky so there's no need to allow dismissing it. We can review if necessary.

Video:
https://user-images.githubusercontent.com/3636549/140498317-941eab7d-20f5-4e10-91dc-e434ea98ed3a.mov

Prototype:
https://www.figma.com/proto/0jsTPLtwz6Bljndkbr1COn/open-source-DS-%5BWIP%5D?page-id=101%3A41568&node-id=101%3A41572&viewport=501%2C48%2C0.58&scaling=scale-down&show-proto-sidebar=1&starting-point-node-id=101%3A41572

Figma file:
https://www.figma.com/file/0jsTPLtwz6Bljndkbr1COn/open-source-DS-%5BWIP%5D?node-id=101%3A41569

![image](https://user-images.githubusercontent.com/3636549/140498784-78f565c7-248b-4905-9146-b4cf577c796e.png)
![image](https://user-images.githubusercontent.com/3636549/140499329-3a2a1d03-7038-408b-971c-313ec5726570.png)
![image](https://user-images.githubusercontent.com/3636549/140499980-1b7074c2-9044-4bb3-8f65-1b574da6c8ec.png)

**Comment by legnaleama** [comment]
@jpvajda quick addition to the above, @ahaberko and I have discussed this a little and we both think it would be good to have a fallback option in case the JP version is not good enough by providing a link to the original source. She'll work on the copy and I'll update the mockup accordingly but it would be just adding a link within the description portion of the callout.

**Comment by jpvajda** [comment]
@legnaleama this is awesome! love it. We did run the language by the UI-Writing team and that input is in  JIRA - UIWRITE-1411

**Comment by legnaleama** [comment]
@jpvajda Quick update with the new language:
![image](https://user-images.githubusercontent.com/3636549/140735771-e21805d5-4487-42a5-b804-5be95d484806.png)
![image](https://user-images.githubusercontent.com/3636549/140736210-cda006cc-ee77-4248-b19f-27e30784e7fd.png)

Figma: https://www.figma.com/file/0jsTPLtwz6Bljndkbr1COn/?node-id=132%3A42586

**Comment by jpvajda** [comment]
@legnaleama Thank you!

**Comment by roadlittledawn** [comment]
@jmiraNR is verifying with Legal re: the verbiage of the disclaimer

**Comment by jpvajda** [comment]
@legnaleama we had a question relating to the screenshots with different button treatments, can you confirm what the approach is, and point to the most current design?

**Comment by rudouglas** [comment]
@legnaleama confirmed the current design is the one in the description. You can see it in the Figma here under `Translation message - new language`

https://www.figma.com/file/0jsTPLtwz6Bljndkbr1COn/open-source-DS-%5BWIP%5D?node-id=132%3A42586

**Comment by jmiraNR** [comment]
Hello, Checking that we can have a hyperlink within the disclaimer. Thank you.

**Comment by roadlittledawn** [comment]
@jmiraNR yep and in fact the current design has a link to the english version of the translated page. what link were you thinking we may want?

**Comment by roadlittledawn** [comment]
this is 90% done in `clang/mt-disclaimer`. remaining things include:
* get finalized copy and translated copy
* figure out how to deal with `Link` component automatically localizing href used in English version link in callout body

**Comment by jmiraNR** [comment]
Hello. I'm hoping to have the MT disclaimer message tomorrow Friday.
@roadlittledawn: We will need a new page under the Japanese Legal "folder" with a "long form" legal disclaimer. That page would only live on the Japanese site (no equivalent in English) and will have to be kept `ON` despite no English parent page.
Cc @austin-schaefer FYI

**Comment by roadlittledawn** [comment]
Updated english copy (includes 2nd link to TBD "long form" legal disclaimer doc. Julien is going to work with legal to genericize the long form doc content he received so we only need one file for all languages.

**Comment by roadlittledawn** [comment]
Julien got okay to genericize "long disclaimer" doc/page yesterday, but he's meeting with @Broseberg today to chat a bit about it. Pending getting that page in place and updating the link in the disclaimer, this will be good to go

**Comment by roadlittledawn** [comment]
PR for long disclaimer doc: https://github.com/newrelic/docs-website/pull/5214
