### ISSUE TITLE
Translation workflow is adding characters to the metaDescripton frontmatter

### ISSUE THREAD

**Issue by LizBaker** [newrelic/docs-website#2599]
This may be happening in the deserialize step [where we manipulate the frontmatter](https://github.com/newrelic/docs-website/blob/8271d9969e1da32483459a0db461e131b867dfe3/scripts/actions/deserialize-html.js#L71) to remove the translate and redirects fields.
`metaDescription: 'In 2020, New Relic changed their pricing plan and account/user model. This is an explanation of those changes.'`
becomes
`metaDescription: >-`  
`In 2020, New Relic changed their pricing plan and account/user model. This is  an explanation of those changes.`

[example PR](https://github.com/newrelic/docs-website/pull/2594/files#diff-b5689162f1309b69ac724e18bce34a7d9ce01de4fd330f51d92433d3a20c4cacR7)

### References

https://yaml-multiline.info/

### Acceptance Criteria 

- [ ] Do discovery work to understand why this occurring
- [ ] No changes are made to the metaDescription frontmatter with the use of `>-`

Need to clarify....

If this is valid, can someone contribute a file with this syntax?
If the addition is “if >- is already there, leave it unchanged”

**Comment by jpvajda** [comment]
@LizBaker does this character inclusion break anything or is just a cosmetic issue?

**Comment by jpvajda** [comment]
If it's just cosmetic I'd put this at a P3, if it's breaking functionality I'd say it's a P2.

**Comment by rudouglas** [comment]
`>-` indicates a multiline string in YAML with no newline at the end (so stripped)

**Comment by rudouglas** [comment]
`>-` is a valid way to describe a string in YAML files, however it functions differently to `|-`  as it describes a single line string as a multiline only in a visual way.

```yaml
metadescription: >-
    This
    is
    a
    string
```

It tells it to interpret `new lines` as spaces with **no trailing new line**, which is the same as writing:

```yaml
metadescription: 'This is a string'
```


_______
```yaml
metadescription: >
    This
    is
    a
    string
```

Tells it to interpret `new lines` as spaces with **trailing new line**, which is the same as:

```yaml
metadescription: |
    This is a string
```

________
When we deserialize with [js-yaml](), the reason it is converting to `>-` is because there is a default `lineWidth` set to `80 characters`. So any single line string over this length is shown with `>-` format instead. Setting the `lineWidth: -1` should mean both:

```yaml
metaDescription: 'In 2020, New Relic changed their pricing plan and account/user model. This is an explanation of those changes.
metaDescription: >-  
    In 2020, New Relic changed their pricing plan and account/user model. This is  
    an explanation of those changes.
```

Deserialize to:

```yaml
metaDescription: 'In 2020, New Relic changed their pricing plan and account/user model. This is an explanation of those changes.
```

____
If a user originally uses the `>-` format it won't maintain that, but they should understand that both are interpreted as the same.

**Comment by rudouglas** [comment]
You can test this here https://stackblitz.com/edit/node-uzq9i3?devtoolsheight=33&file=deserialize.js

Just run `node deserialize.js` in the console

Change the `markdown.yml` file to test different inputs
