### ISSUE TITLE
Confusing links between `New Relic in practice > UI and data` and `New Relic One > UI data` 

### ISSUE THREAD

**Issue by fightingmonk** [newrelic/docs-website#2667]
I got lost trying to navigate the docs menus, not sure if it's the hyperlinks or content that are out of date...

In [New Relic in practice](https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/get-started/introduction-new-relic-one/) there is a nav category called `UI and data`
If I click the `>` on the menu category I see these options under that menu section:

- Basic UI features
- Distributed tracing
- Maps in context
- Supported browsers
- Dependencies page
- Normalization rules
- Service maps
- EOL announcements

But if I click on the words `UI and data` in the menu I'm taken to a [section of the NR1 docs](https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/ui-data/) that has a completely different set of content.

## Expected behavior

Based on my experience w/ other docs site content, I'd expect that clicking the category `UI and data` should stay inside the `New Relic in practice` section and show a summary page and maybe links to the 8 content docs within that section of the menu.

**Comment by paperclypse** [comment]
This is related to #2668

**Comment by zuluecho9** [comment]
@roadlittledawn This was one you might have some input on. Looking at this one, I'm not actually sure why it wouldn't work correctly like other ones.

**Comment by roadlittledawn** [comment]
the site structure was reworked quite a bit since this was file. we also deployed an update so left nav menu data is used to populate the index page menus. so i think this was likely fixed. i'll close for now, but if you notice any more weird menu-ing, @fightingmonk , please let us know! 

also, just a heads up, in the next month or so, the site is going through another big round of content structure changes as well.
