### ISSUE TITLE
Revert sidebar behavior: Expand menus, rather than click deeper

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#2668]
(Not ready for implementation yet, filing this issue as a place to gather feedback.)

### Is your feature request related to a problem? Please describe

We've had a fair amount of feedback now that people preferred the old sidebar behavior (clicking on category titles expands the menu, but does not open the category in main column). 

### Describe the solution you'd like

Change back to old behavior, while keeping the nifty category menus accessible via URL hacking.

**Comment by roadlittledawn** [comment]
FWIW. it's probably not obvious but you can open the just the menu by only clicking on the caret/arrow and not the text.
![2021-06-11_14-15-50](https://user-images.githubusercontent.com/2952843/121749464-8e4e6a00-cabf-11eb-89e8-cb7d4346191d.png)

**Comment by austin-schaefer** [comment]
@roadlittledawn For sure! I actually prefer the new model FWIW, but have gotten a fair amount of feedback asking us to revert to the titles also expanding the menu.

**Comment by zuluecho9** [comment]
I may be stating the obvious, but I'm not actually sure how we or others would easily get the URLs for these index/category views without the current functionality. How would we get them?

**Comment by austin-schaefer** [comment]
@zuluecho9 : I think if we did this, the only way to get there would be URL hacking. We could restore the "breadcrumb" pattern from the old site, perhaps? Although in my experience very, very few people knew it existed.

**Comment by zuluecho9** [comment]
> @zuluecho9 : I think if we did this, the only way to get there would be URL hacking. We could restore the "breadcrumb" pattern from the old site, perhaps? Although in my experience very, very few people knew it existed.

Yes, that makes sense. If the current functionality still existed under the hood, just without the sidebars being clickable, then we'd just have a manual way to figure out those URLs and use them. As long as there's a way for us to easily get those category/index views and be able to use them.

**Comment by zuluecho9** [comment]
To highlight one problem we have with the current functionality: 

Sometimes there are cases when the folder structure doesn't exist at all for a specific nav file category. For example, there might be a subcategory in a nav file that has no equivalent folder structure, and is just used as a place to put docs that redirect to other categories. When this happens, this can result in a taxonomy/category URL that 404s. 

The solution to this is (as far as I know) either: a) create a "dummy" folder structure in the desired section, with a dummy doc redirecting to the desired doc, because the system needs to find a folder structure and doc in that place to work properly, or b) erase the 'path:' field for that category in the nav file, which will result in that category not being clickable and just work as a typical expander/collapser header, and not be clickable when seen in higher level index/category views (see image). 

I point this out just to emphasize how there are some hidden costs and weird solutions involved with current implementation in trying to make sure we're consistent/aligned. Preferably we wouldn't need to create a dummy folder structure and dummy doc just to make sure the sidebar functionality and category/index views were working okay and consistent. 

<img width="377" alt="Screen Shot 2021-06-15 at 8 23 05 AM" src="https://user-images.githubusercontent.com/9435570/122083017-5a23c380-cdb5-11eb-937c-d9a5deb9f8a6.png">

**Comment by austin-schaefer** [comment]
Nice try stalebot

**Comment by austin-schaefer** [comment]
Closing in favor of #3400 which has a better solution
