### ISSUE TITLE
Complete Benchmarking on Gatsby v3.5

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2742]
We did some thorough benchmarking on the docs site build times recently but at the time we ran these tests we did not upgrade the site to Gatsby 3.5, let's run benchmarks on this newest version of Gatsby. 

### Acceptance Criteria

- Complete benchmark tests on Gatsby V3.5
- Update the [wiki with data](https://github.com/newrelic/docs-website/wiki/Benchmarking-Build-Times)

**Comment by jpvajda** [comment]
@rudouglas would you mind finishing the benchmark now that we are on gatsby 3.5 on the docs site?

**Comment by rudouglas** [comment]
I entered my build times but we may want to recheck these when I get my new laptop.

Other options would be to use OpenTelemetry so that we can collect this data everytime we build by default which would be much more useful and less time consuming, or spin up a dedicated EC2 instance for clocking this

**Comment by jpvajda** [comment]
@rudouglas + 💯  for using open telemetry. that be really cool to have that data to measure build times holistically. for now i think we are OK with this general data you provided to get some data to Gatsby for general benchmarks, but longer term i like the idea of tracking build times for all our sites with New Relic.

This could be part of an Olly Pack as well for Gatsby 🥇

**Comment by jpvajda** [comment]
Oh I see the times went up, I don't know much about your laptop struggles, but it seems this data really isn't useful unless we compare the build times on a similar set of hardware.

**Comment by rudouglas** [comment]
@jpvajda I reran the tests yesterday and monitored CPU and RAM and didn't seem to be running into any issues as far as I could see, so in my mind this is as close to the previous tests as we can get.

Some steps are quicker, but the site is also slightly bigger so I wonder if the times are not much different because of that? The improvements they made may also not be applicable to our setup, as I know some Feature Flags already don't improve things for us.

💯 I think a dedicated EC2 for testing builds and OpenTelemetry to capture the data more easily would be the best way forward

**Comment by jpvajda** [comment]
@rudouglas do you want to create a ticket for that idea? maybe slap the `innovation` label on it. 🥳
