### ISSUE TITLE
Checks on release PRs are stalling

### ISSUE THREAD

**Issue by LizBaker** [newrelic/docs-website#2932]
Multiple release PRs have gotten stuck on the 2 required checks for main. So far all PRs also had the last commit coming from the opensource bot (update whats new ids) which may be related. Closing and reopening solves the issue but it'd be nice to avoid all together

This seems to be only occurring on PRs from `develop` to `main`

### Acceptance Criteria

- [ ] PRs should not get stuck on required checks

**Comment by nr-kkenney** [comment]
i think i got to the bottom of this issue:

the stalled prs are due to the commit coming from the bot. github has a mechanism built in:
>An action in a workflow run can’t trigger a new workflow run. For example, if an action pushes code using the repository’s GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

this safeguard prevents a workflow from triggering itself endlessly (automatically). 

but what was weird is that it looks like we arent using github token when we commit, we are using opensource_bot_token:
```none
- name: Push Commit
        if: steps.commit-changes.outputs.commit == ‘true’
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
          branch: develop
```

so if we are using a PAT, how are we running into this issue? well, it turns out, we actually arent using the PAT (even though we explicitly set it in the above code block 🙈 . the github checkout action caches github_token, which is used when we do a push. so we are hitting that case where an action cannot trigger a workflow run.

that means the whats-new workflow is currently in the scenario where it commits a push, but that is unable to trigger the validation workflow.

since the status check of the pr is based on the last commit added, and the last commit added is by the bot, it looks like its stalled — the bot commit doesn’t trigger any of the push workflows to run.

the fix:
we need to prevent the checkout action from caching the token so that we can use the PAT, and we need to prevent the action from triggering the workflow its in, to prevent an infinite loop. both of these are easily achieved: the action has a parameter we can use to turn off the credential cache, and we can change the trigger type on the workflow so that it doesnt trigger on push.

references:
- [github checkout action](https://github.com/actions/checkout)
- https://github.community/t/push-from-action-even-with-pat-does-not-trigger-action/17622/4
- https://docs.github.com/en/actions/reference/events-that-trigger-workflows
