### ISSUE TITLE
Tags NRQL syntax is not explained

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#3004]
### How can we make our docs better?

If this actually IS explained in the docs somewhere and I've missed it, show me where and show me the door! I'll be happy to just know where it is.

However, I haven't been able to locate it and this is vitally necessary, as many customers use label or tag values in NRQL queries and dashboards.

Labels could be queried by using a WHERE clause like: WHERE myLabel = 'myValue'\
Tags need to be queried a little differently, like: WHERE tags.myTag = 'myValue'

Please include this detail somewhere in the docs! (or show me where it is already and then tell me to buzz off -- I'm fine with that option)

### Jira migration info

Migrated from Jira DOC-5918

**Comment by ahunger603** [comment]
@austin-schaefer NRQL syntax has no tangible distinction between `myLabel` and `tags.myTag`, these are both identifiers, and are executed the same (Though there are cases where compound identifiers behave differently). There is no concept of label / tag in the syntax or execution. 

You may want to consult the documentation for the integration / product that is publishing the telemetry you're querying. When generating the data, they have control over how the attributes are populated, and how / why any values would be prefixed with `tags`.

**Comment by zuluecho9** [comment]
@austin-schaefer This is talked about somewhat in jira DOC-7132. To my knowledge, it was only really possible to tag APM tags via NRQL, so we have info in that doc about that. (otherwise, this wasn't possible unless we were talking about common attributes that are also made available as tags, but that's just about querying attributes). Though it's come to my attention that apparently this 'query tags' functionality also seems available for synthetics data, and possibly other data sources, so that's what that jira is about. 

The challenge is that the tag implementation varies so much from data source to data source. It is hard to talk about tags as a whole because the implementation varies so much.

**Comment by dbarnesbrownNR** [comment]
@zuluecho9 and @austin-schaefer have we arrived at a decision about needed edits? Might be good to list action items focused on what a PR should contain in description or a comment since we're doing 1-day hero rotations and I don't want this to get buried but also do not expect an instantaneous turnaround. Thanks!

**Comment by zuluecho9** [comment]
We have a jira for this. DOC-7312. This has been harder to get to the bottom of than you'd think. Considering we have a jira for this, would you be okay with closing it @austin-schaefer ? (I know that's not the usual route but figured you might be okay with it)

**Comment by bradleycamacho** [comment]
@dbarnesbrownNR @zuluecho9 Can one of you two provide a status update on this? I'm not sure why we converted this issue from a jira and then just refiled another jira.

**Comment by dbarnesbrownNR** [comment]
@bradleycamacho I think we were struggling on this one to figure out what the scope was and it really requires a bit more looking into because it's important and I or whoever covers it will need a better idea of the technical details before we proceed. @zuluecho9 the Jira mentioned seems to cover another area, is there another Jira issue that might be the correct one? If you can provide some clarity on that let's just move the correct Jira under my name for backlog grooming for next sprint and close this issue.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
