### ISSUE TITLE
CSAT feedback: requests for info on Browser 

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#320]
The same user provided two sets of feedback about the Browser docs. This feedback:

> Is browser application measuring cached or non-cached page load (e.g.. does it always load all images, or does it cache them)? What is throughput useful for? How is this measured? e.g. what does 600ppm tell me? it doesn't seem to correspond to the actually number of page views seen by the server.

About this page:https://docs.newrelic.com/docs/browser/new-relic-browser/page-load-timing-resources/page-load-timing-process

> And this feedback:ppm throughput is shown in the browser section, but there seems to be no documentation to say what this is, how it is calculated or measured, or what it can be used for.

Related to general search.

We have info on caching in the Browser docs, but I couldn't find info to answer his other questions about understanding PPM. 

## Action items

1. Add info to help define throughput and PPM in the Browser section.
2. Get it reviewed by SME.

## Jira migration details

This issue was migrated from the internal DOC jira project:

* Original reporter: @mmfred
* Jira ticket ID: DOC-5253
* Original priority: Medium
* Original component: Experience Debt
* Original product group: FSO

**Comment by CherylFrankenfield** [comment]
We have throughput information here: 
https://docs.newrelic.com/docs/browser/browser-monitoring/getting-started/browser-summary-page/

The underlying query on the browser throughput summary chart is: 
SELECT rate(count(*), 1 minute) FROM BrowserInteraction WHERE (appId = X) AND (`mobileOptimized` IS NULL) AND (category IN ('Initial page load', 'Route change')) SINCE 1800 seconds AGO FACET CASES (WHERE category = 'Initial page load' AS 'Initial page load', WHERE category = 'Route change' AS 'Route change') TIMESERIES EXTRAPOLATE

More info here: 
https://docs.newrelic.com/docs/new-relic-solutions/get-started/glossary/

 page views per minute (PPM) for Browser

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
