### ISSUE TITLE
[In Product XP] Some What's new posts aren't rendering correctly on Docs Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3307]
It looks like some what's new posts are missing body content. 

`NOTE` [The doc site is rendering this data correctly](https://docs.newrelic.com/whats-new/2021/06/data-ingest-drill-down/)

### Steps to Repro

1. go to new [relic one > documentation & support ](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5saXN0aW5nIiwiZmF2b3JpdGVzIjp7InNlbGVjdGVkIjpmYWxzZSwidmlzaWJsZSI6ZmFsc2V9LCJsYXN0Vmlld2VkIjp7InNlbGVjdGVkIjpmYWxzZSwidmlzaWJsZSI6ZmFsc2V9fQ==&overlay=eyJjb250ZXh0TmVyZGxldElkIjoibnIxLWNvcmUubGlzdGluZyIsImNvbnRleHREaXNwbGF5TmFtZSI6Ik5ldyBSZWxpYyBFeHBsb3JlciIsIm5lcmRsZXRJZCI6Im5yMS1oZWxwLXhwLmhvbWUiLCJzZWFyY2hUZXJtIjoiY29udHJvbCBkYXRhIGluZ2VzdCIsImN1cnJlbnRBcnRpY2xlVGl0bGUiOiJDb250cm9sIGRhdGEgaW5nZXN0IGNvc3RzIHdpdGggaW5nZXN0IGRyaWxsLWRvd24ifQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5jYXRlZ29yaWVzIiwicm9vdE5lcmRsZXRJZCI6Im5yMS1jb3JlLmxpc3RpbmciLCJmYXZvcml0ZXMiOnsic2VsZWN0ZWQiOmZhbHNlLCJ2aXNpYmxlIjpmYWxzZX0sImxhc3RWaWV3ZWQiOnsic2VsZWN0ZWQiOmZhbHNlLCJ2aXNpYmxlIjpmYWxzZX19)
2. search control data ingest
3. see missing content

### screenshots

<img width="1649" alt="Screen Shot 2021-07-28 at 10 58 34 AM" src="https://user-images.githubusercontent.com/1395158/127377373-f966be2a-8d50-478e-8a50-3bf473158d66.png">

### Expected

All What's new posts render correctly.

**Comment by jpvajda** [comment]
@zstix is troubleshooting it was brought our attention by Bill and Nic and Mark B so it's higher priority .

**Comment by zstix** [comment]
The pages that fail to display in the help overlay aren't regular docs pages, they're "What's new" announcements. These pages are special in that they live in a different part of the repository and have their own endpoint for getting the JSON content.

The service that powers the in-product help is unaware that these are special pages, and it's attempting to get the content for (what it thinks is) a page (when it's really a post). Here's the query that the in-product help experience is using:

```graphql
query ($id: ID!) {
  docs {
    library {
      article(id: $id) {
        url
        id
        title
        body
      }
    }
  }
}
```

And when you provide it an ID for a what's new posts, will return `body: null`. Here's an ID to test that out:

```json
{
  "id": "RE9DU3wvd2hhdHMtbmV3LzIwMjEvMDYvZGF0YS1pbmdlc3QtZHJpbGwtZG93bi98NjBlNWI2NjMxOTZhNjc5NWM4NGVhMDgy"
}
```

In order to remedy this, we have possible solutions:
🅰️ We update the service so that, if it determines that an "article" is a what's new post, it uses a _different_ JSON endpoint to get the content.
🅱️ We update the service so that it doesn't show what's new posts when searching for help to show the user (the links will still be present in the left sidebar).

@jpvajda Your call on which path you want to go down and when you think we should do this work.

**Comment by jpvajda** [comment]
Let's go with 🅰️
