### ISSUE TITLE
update triage to localization project workflow

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#3392]
### Background
Triaging to the localization project has recently started to fail. As an example: https://github.com/newrelic/docs-website/runs/3233399222?check_suite_focus=true. This appears to be due to the column name changing so the workflow is currently looking for a column that no longer exists. We should update it to reflect the new name so the workflow can run without failure.

### Acceptance Criteria

- [x] Update [Docs Site Localization PRs and Issues](https://github.com/newrelic/docs-website/projects/4) to use new column name.
- [x] Get workflow to run successfully

**Comment by jpvajda** [comment]
I got this one.

**Comment by jpvajda** [comment]
If someone else wants to take this feel free. 😅

**Comment by rudouglas** [comment]
haha the timeline on your comments looks like you spent 6 hours sweating over this before you gave up 😂

**Comment by rudouglas** [comment]
This is failing because the `COLUMN_NAME` in [Docs PRs and Issues](https://github.com/newrelic/docs-website/projects/3)(Hero to triage) is different to [Docs Site Localization PRs and Issues](https://github.com/newrelic/docs-website/projects/4)(Needs Triage) but the workflow is expecting them to be the same. @bradleycamacho it looks like you made the [change in the script](https://github.com/newrelic/docs-website/commit/2d081a04bd93b98c222f06a973d545795274d77f), would it make the most sense to just change the column name in `Docs Site Localization PRs and Issues` to `Hero to triage`?

**Comment by bradleycamacho** [comment]
Gah, sorry we didn't realize there was so much relying on the column name when we switched that recently.

If @jmiraNR is ok with changing the column name in **Docs Site Localization PRs and Issues**, that may be the easiest option.

Otherwise, we can also change the docs column back and revert the changes to the script.

**Comment by jmiraNR** [comment]
@bradleycamacho @rudouglas Hi, I'm not sentimentally attached to the column name. Feel free to rename. Thank you for checking.

**Comment by rudouglas** [comment]
Great thanks @jmiraNR @bradleycamacho i've changed the column name and rerun the workflow which is successful now. I think it's safe to close this issue out but let us know if there's anything else you need :)
