### ISSUE TITLE
Fix broken release workflow

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#3398]
## Description

The release workflow is erroring. Possibly another unescaped character borking things?

https://github.com/newrelic/docs-website/actions/workflows/release.yml

## Example error message
```
/bin/bash: -c: line 93: syntax error near unexpected token `('
/bin/bash: -c: line 93: `@bradleycamacho - Revert "Updates for Android Agent 6.2.0 release (#3349)" (#3353) [->](https://github.com/newrelic/docs-website/commit/6ce374ee544b2e51e1410f8af8962ea6ad8c4ad7)'```

**Comment by roadlittledawn** [comment]
@austin-schaefer mentioned he's okay with removing this workflow if needed

**Comment by austin-schaefer** [comment]
(I'd prefer to keep it or course, but if it's a source of major overhead then I'm willing to forego it.)

**Comment by jpvajda** [comment]
What is the purpose of this workflow? it's label "release" and seems to be about the github release flow we are ripping out with this ticket i think? @roadlittledawn 

https://github.com/newrelic/docs-website/issues/3415

**Comment by rudouglas** [comment]
No @jpvajda this workflow is to create the GitHub release notes when we merge from `develop` to `main` 
https://github.com/newrelic/docs-website/releases

So wouldn't be affected by the GitHub builds. This issue was caused by `""` quotation marks being used in a commit description which we need to escape.

using the `json` module should allow us to encode the description strings before we process them which should escape any characters that would normally break a string pattern

**Comment by rudouglas** [comment]
This was still failing so i did some extensive testing and the json approach didn't seem correct. I changed to just escaping the `"` chars as they were the only special characters causing issues.

I also changed the release command to run from within the script as there were weird issues between strings in python and strings in bash

**Comment by jpvajda** [comment]
What's blocking us from getting this to done @rudouglas ?
