### ISSUE TITLE
Issue: record_exception (Python agent API)

### ISSUE THREAD

**Issue by ElementalWarrior** [newrelic/docs-website#3467]
You've removed all the documentation for the deprecated newrelic.agent.record_exception. For those of us who aren't running the bleeding edge python package we now can't refer to the documentation. 

https://docs.newrelic.com/docs/agents/python-agent/python-agent-api/recordexception-python-agent-api/

This link no longer tells me anything remotely useful about the parameters of the function. What is the difference between value and params? 

I cannot find a link to documentation for the version that is running on our services. Am I supposed to dig through https://github.com/newrelic/docs-website at a point in time based commit looking for this?

### Tell us what you need

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/python-agent/python-agent-api/recordexception-python-agent-api/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @ElementalWarrior, here's the PR with this change. In it, you can find the information that was removed: https://github.com/newrelic/docs-website/commit/33105490b9a6c5929af6044e58019f7b31efe6e4#diff-7654c234bf4f9f858956e83311f0d4dac15ae52ae67240db748ff37389b29541

Because this is deprecated, I'd say that the documentation is correct here. In general, we recommend that people update to the latest version.
