### ISSUE TITLE
Migration scripts don't handle fenced code blocks within MDX well

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#347]
### Description

The NRQL syntax doc has some complicated syntax within collapsers, and the migration script is getting confused and pulling in all the content as code.

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions
2. Compare with https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions

### Expected behavior

New doc should reproduce formatting/hierarchy of old doc.

### Considerations

- This functionality is now available in MDX  https://github.com/mdx-js/mdx/pull/1367

### Useful links

* [MDXv2 Umbrella Issue](https://github.com/mdx-js/mdx/issues/1041)

**Comment by tariqahmed** [comment]
Isn't this the same issue as

https://github.com/newrelic/docs-website/issues/116

?

**Comment by jerelmiller** [comment]
@tariqahmed not quite. This one has to do with the rendering of a fenced code block when used inside of a JSX element. In this case, either the parser or formatter is a bit off and instead of rendering a block of code, it envelops a bunch of the surrounding markup as well. You can see the issue at play here: https://github.com/mdx-js/mdx/issues/1283

#116 is asking for the code blocks to support rendering `var`, `mark` and `a` tags inside of them. This isn't as much a rendering issue (bug) as it is a feature request.

**Comment by jpvajda** [comment]
This functionality is now available in MDX : https://github.com/mdx-js/mdx/pull/1367

**Comment by jerelmiller** [comment]
As soon as they push out a new version, we can go ahead and update.

**Comment by tariqahmed** [comment]
Effort basically involves:
- AST names changed, look at those and adjust migration script
- Upgrading MDX
