### ISSUE TITLE
Fix related resources action

### ISSUE THREAD

**Issue by LizBaker** [newrelic/docs-website#3712]
The fetch swiftype results action (related resources script) hasn't run successfully in about a month https://github.com/newrelic/docs-website/actions/workflows/fetch-swiftype-content.yml

AC
- [x] research cause of issue
- [x] create a fix

**Comment by rudouglas** [comment]
The related resources workflow has been failing for the last ~month, seems like this was due to an incorrect redirect url that had no leading slash ([this one](https://github.com/newrelic/docs-website/pull/3726/files). When `normalizeUrl` is called on it [here](https://github.com/newrelic/docs-website/blob/645e2c2ed3ad390fa28714786edb376062ad2bf9/scripts/actions/get-related-resources.js#L118) it runs it through `appendTrailingSlash()` which runs it through [hasQueryParams()](https://github.com/newrelic/docs-website/blob/645e2c2ed3ad390fa28714786edb376062ad2bf9/scripts/actions/utils/related-resources-helpers.js#L1). This tries to create a new URL from it but errors because it's invalid without the leading slash. 

Because the issue was with a redirect, and [getExcludedUrls()](https://github.com/newrelic/docs-website/blob/645e2c2ed3ad390fa28714786edb376062ad2bf9/scripts/actions/utils/related-resources-helpers.js#L27) gathers these from the frontmatter, I added a check here to add a leading slash if needed
