### ISSUE TITLE
Throttling the ingestion of kubernetes events

### ISSUE THREAD

**Issue by kyranb** [newrelic/docs-website#3874]
### Tell us what you need

I've having trouble determining how to throttle the `metrics` being sent to New Relic.

I'm running a cluster where 75% of the data ingested is coming from the kubernetes metrics integration.

I don't need second by second visibility. Am I missing something or is there a way to throttle how often data is sent to new relic?  
 
### Anything else you'd like to share?

![Screen Shot 2021-09-11 at 12 31 10 pm](https://user-images.githubusercontent.com/5426926/132933267-8dae04cd-c5bb-4bad-89d8-a9e0b3f91ead.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/kubernetes-integration/troubleshooting/

**Comment by roobre** [comment]
Hi @kyranb!
Thaks for raising your concerns over this. If I'm not mistaken, the usage for `Metrics` here should correspond to the prometheus metrics captured by `nri-prometheus` in you kubernetes cluster. This can happen if you have many services exporting large amounts of Prometheus metrics in your cluster, as those will be automatically found by `nri-prometheus` and scraped for you.

There are several ways in which this can be reduced:
1. Remove the `prometheus.io/scrape` label from pods or services you don't want metrics from.
2. Reconfigure `nri-prometheus` so it looks for a different label, which is useful if you still want some prometheus server collecting those metrics.
3. As a last option, you can also write rules in the `nri-prometheus` config to drop metrics based on a prefix. I do not particularly recommend this over changing the label because it's slightly more fragile.

If you want to know an estimation of which prometheus service is using the largest amount of storage, you can check with:

```
FROM Metric select bytecountestimate() FACET targetName WHERE clusterName = 'YOUR_CLUSTER_NAME' SINCE 1 day ago
```

`targetName` should be the pod or service name as discovered by `nri-prometheus`.

It is true that this should be better captured in the docs [https://docs.newrelic.com/docs/integrations/prometheus-integrations/install-configure-openmetrics/configure-prometheus-openmetrics-integrations/](here). Our team is planning a significant effort soon to overhaul our integration docs pages, and I will add this item to the task list :)

Please tell us if this does not help solving the problem.

**Comment by kyranb** [comment]
Thanks so much :)

I came across this too which may help other folks that stumble on this issue too:

https://discuss.newrelic.com/t/reduce-the-amount-of-ingested-data-by-kubernetes-integration/127217/6
