### ISSUE TITLE
Gatsby build issues

### ISSUE THREAD

**Issue by mmfred** [newrelic/docs-website#4070]
This issue problems we're seeing with Gatsby builds. One thing we noted in discussion is that when a build gets "fixed" there is often not a way to track the problem that was happening. So when you add to this issue, please provide a link to the PR, and a description of what happened or is happening, and how you fixed it. 

**PR**: Release to main: https://github.com/newrelic/docs-website/pull/4035
**Problem**: several of the PRs in the PR from the Develop branch to the Main branch were listed as broken, but when I drilled down into them, they had passed the checks. I talked to Alba, who confirmed this. I closed and then reopened the release PR, and then it build and was fine. But you can still see the PRs that are listed as failing, despite that they didn't fail initially.

**PR**: https://github.com/newrelic/docs-website/pull/4045
**Problem**: This PR got hung up and I had to close and reopen it. I think this is because after the first commit, the checks began, and then another commit was added.

**Comment by rhetoric101** [comment]
@mmfred, here are some additional examples of mysterious issues:

* [PR 3811](https://github.com/newrelic/docs-website/pull/3811/checks?check_run_id=3625059031) and the related [Slack discussion](https://newrelic.slack.com/archives/C01R2TB8BUZ/p1631827425199200). It turns out I was able to close and reopen the PR to unstick this.
* [PR 3817](https://github.com/newrelic/docs-website/pull/3817) and the related [Slack thread](https://newrelic.slack.com/archives/C01R2TB8BUZ/p1631121114130500) indicated that although I kicked off this build around 8:00 at night, another merge must have interfered (perhaps from the Barcelona team?). This points to the fragility of our process.

**Comment by bradleycamacho** [comment]
#4116 - This one really hurt. This was a last minute breaking change, and the build stalled out for upwards of an hour. Strangely enough, I noticed this one NEVER even started. It was eternally stuck in "waiting for queue.

**Comment by bradleycamacho** [comment]
#4200 : The build just canceled itself randomly. No idea why.

**Comment by bradleycamacho** [comment]
#4200 never completed the check after restarting. After I restarted the check, it just got stuck in a queue and never started up.

**Comment by barbnewrelic** [comment]
This one has been spinning https://github.com/newrelic/docs-website/pull/6536 so I'm putting here as an FYI. As it turned out, another contributor edited the file right after I did, and his build did build. So I'm going to merge his and redo mine without duplicating his edit.
