### ISSUE TITLE
Issue: Dashboard API migration: from Insights API to NerdGraph

### ISSUE THREAD

**Issue by kaschaefer** [newrelic/docs-website#4264]
### Tell us what you need
On the Dashboard API migration page, there's a section of bullet points with some of the details of the migration. The third bullet point, which starts out "The REST API for Insights is not affected...", starts to tell the reader to go somewhere else for more information, but never actually says where to go. It just says, "For more information about which key to use with our APIs, see our documentation about **.**" Seems like maybe there's a piece missing there.

### Anything else you'd like to share?
It would also be super helpful if a link could be included to a page that describes the difference between the Dashboard API and the REST API for Insights queries, because as a reader it's not clear to me what the difference is.

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).
![image](https://user-images.githubusercontent.com/28942464/136844149-89a8a490-563e-4d65-99e9-63375a91db2b.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/dashboards-api-migration-insights-api-nerdgraph/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 94.0.4606.71
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@kaschaefer Regarding your question about the difference between the Dashboard API and the Insights query API: the Insights query API (https://docs.newrelic.com/docs/apis/insights-apis/query-insights-event-data-api/) is a way to query New Relic data via NRQL; it has been mostly deprecated because NerdGraph is now the recommended API for that. The Insights Dashboard API, which is deprecated now, was related but was specifically about building/managing dashboards, which is related to NRQL-querying but not exactly the same. The Insights Dashboard API was specifically about some dashboard/widget/visualization-related things, whereas you could theoretically query New Relic data via NRQL without a dashboard being involved. Hope that helps.
