### ISSUE TITLE
Include Infrastructure agent in Agents section

### ISSUE THREAD

**Issue by danifitz** [newrelic/docs-website#438]
### Is your feature request related to a problem? Please describe

At the top level navigation, there is a link to `Agents`. When I click on this, I only see APM agents. As a user, I'd also expect to find a link to the Infrastructure agent, it is an agent after all! https://docs-preview.newrelic.com/docs/agents

### Describe the solution you'd like

Include a link to the infrastructure agent.

### Describe why this important to you

It logically makes sense to list all the agents NR offers under the agents link. Omitting Infrastructure enforces org boundaries we've created internally rather than a holistic view a customer would expect.

### Additional context

None.

**Comment by jerelmiller** [comment]
Hey @danifitz! Thanks so much for checking out the preview site! We are greatly appreciative!

We are still in the midst of pulling in content from the existing site to the new docs site, so its expected that some of the docs are still missing. We just merged in a giant PR yesterday (#425) that brings in a bunch more content. Once that is live, that puts us at ~90% of all the content migrated to the new preview site! Its possible the infrastructure agent docs are part of the remaining 10% of content that we have yet to pull in. We are hoping to get to 100% sometime in the near future. The nav currently reflects only the content we've already migrated.

I'll keep you in the loop when we bring in some more content so that you can take a look!

**Comment by jerelmiller** [comment]
We are now at 100% of content migrated! As for making sure the integrations docs end up in the right place, that should be captured as part of #587. I'm going to go ahead and close this issue.
