### ISSUE TITLE
Create an internationalization folder and Japanese subfolder

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#478]
## Description 
We need a folder to store our translated content. There are a few different ways that we can map this out. We can take all of our `/content` folder and split it into two folders `/en` and `/jp`. Or we can create a separate `/internationalization` or `/localization` or `/translated_content` folder at the `/src` root and have a `/jp` subfolder. 

## AC 
* [ ] Japanese folder to store Japanese mdx content

**Comment by jerelmiller** [comment]
I'll add one other possibility into the mix. Rather than separate folders, we could use a file extension for the various translated pages.

For example, a file at `src/content/docs/apm.mdx` would have a japanese file at `src/content/docs/apm.jp.mdx`.

Since these live next to each other, it means we wouldn't need to replicate the file structure inside of the translated subfolders to match the english content. This might complicate some of our gatsby config/plugins, but it could simplify it from a content contributors perspective.
