### ISSUE TITLE
Improve Split test rendering "flash" `part 1`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#5165]
When running a split test, like the current sign up button test running on docs.newrelic.com the user expeirences the button rendering the actual split test, and the button quickly flashes as it transitions to the correct treatment. This is related to:

 _Unfortunately, we do have some technical limitations since the site renders at build time before any user actually accesses the site. We could move to just rendering those types of things on the client with a blank placeholder at build time, however that would still change the overall behavior of the test since the initial load would not include the button at all vs the button being immediately available on load when the test isn’t being conducted. At the time, the flash of the default button was considered to be a fine trade off._

### Steps to reproduce

- go to docs.newrelic.com 
- look at the signup button
- you'll see the button quickly render as it changes to the treatment

### References 

https://www.joshwcomeau.com/react/the-perils-of-rehydration/

### Acceptance Criteria 

- [x] Determine if Gatsby 4, with SSR may help us with this problem  

> it won't 

- [ ] AND/OR determine if we can [use the local-storage cach](https://help.split.io/hc/en-us/articles/360058730852-Browser-SDK#configuring-localstorage-cache-for-the-sdk)e option for Split - discuss with @abrunner94 if required.
- [x] Determine if any of the approaches for re-hydration mentioned in the blog above could reduce this issue. `it will not`
- [x] Provide the options for resolving this issue to @jpvajda 
- [ ] Create a follow up ticket to implement this change.

**Comment by aswanson-nr** [comment]
The blog post @jpvajda linked goes over using client only routes to handle dynamic data. This is something we want to use for this split test to avoid the rehydration "flash" that we're currently seeing. Here is a link to the Gatsby Docs on [Client-only routes](https://www.gatsbyjs.com/docs/how-to/routing/client-only-routes-and-user-authentication/)

**Comment by rudouglas** [comment]
Some comments on this, still looking into it but i'm not sure if client-only routes will help us here as we still rely on the splitSDK to be ready before displaying content, the client-only routes doesn't seem to speed that up in any way, there is still a wait time involved where the correct content isn't there. I think the `gatsby-plugin-splitio` may help with that but it requires a `key` that I don't have permission to access.

The `InLocalStorage` option i'm testing out here: https://github.com/newrelic/gatsby-theme-newrelic/pull/614

Other than that we may want to consider a placeholder element so any delay doesn't affect the real-estate of the page

**Comment by rudouglas** [comment]
The split.io docs also call out that the ReactSDK may not be the most suitable for SSR sites with Gatsby, should we be using the NodeSDK instead:

```
For server-side rendering with React use the Node.js SDK.
```

https://help.split.io/hc/en-us/articles/360038825091-React-SDK#language-support

**Comment by aswanson-nr** [comment]
I took a quick look at that plugin and it looks like it just handles setting up the provider, which the theme already does for us. A little worried about the lack of source code on it as well.
I'm still not quite sure how we would use the Node SDK with our static site generation. 

Gatsby even recommends not going with the approach we took in their [A/B testing](https://www.gatsbyjs.com/docs/ab-testing/) docs. They do recommend a branch based strategy that Netlify uses, a similar feature is currently [under review for Gatsby Cloud](https://portal.gatsbyjs.com/gatsby-cloud/p/ab-testing-support)

**Comment by rudouglas** [comment]
@jpvajda our conclusion on this is that it's not currently possible to instantly load the correct treatment for a split test when the page loads, this is because we have to wait for the splitSDK to communicate with the API which we can't speed up client side. The alternative would be waiting until the SDK is ready to load the entire page, which wouldn't be great for UX. Our recommendations are as follows:

### Short Term:
 - Load a skeleton component in place of the treatment component with some sort of indicator that a component is currently loading (Spinner, animation etc.). This is so that there is no shift in real estate when the component loads and no flash between content loads
 - Use the caching feature of the SDK so that this load only happens once per user, and the treatment is loaded from local storage every other time. This should apply across products as well (@josephgregoryii is currently testing this)
 - Use the `isTimeOut` feature of the SDK so that we know to eventually render the default component
 - Needs some design input for best practices

### Long Term:
 - Investigate the use of a branch based strategy, which is currently used by Netlify and a [Feature Request on Gatsby Cloud](https://portal.gatsbyjs.com/gatsby-cloud/p/ab-testing-support) that we could follow up on. If it's similar to Netlify's implementation it would require two separate `main` branches that we would need to maintain
 - Be ok with the load delay

**Comment by jpvajda** [comment]
@legnaleama adding for visibility on this. I think this is a good approach both short and long term. I'll add the FR for Gatsby to our wish list as we are meeting with them this week.
