### ISSUE TITLE
[Github] Add  reusable Slack notification  workflow for `What's new` PMM gatekeepers

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#5250]
relates to https://github.com/newrelic/docs-website/issues/5078

Is it possible to have new "What's new" posts trigger Slack notifications to members of the PMM team?

We are currently using CodeOwners to trigger GitHub notifications/emails to the PMM team, but we're wondering if you could add Slack messages to that, too.

You probably can't choose between GitHub notifications/email and Slack, but we'd like to at least see if you can add Slack messages to this action.

@daynaslord is organizing the self-service effort for "What's new" posts, so you should keep her in the loop.

## Helpful links
- https://github.com/marketplace/actions/slack-notify

### Acceptance Criteria

- [ ] Determine if something already exists to support this in the github marketplace or slack integrations
- [ ] create a re-usuable slack notification workflow. 
- [ ] the workflow should have a parameter to set the channel
- [ ] the workflow should have a parameters to set specific users
- [ ] the workflow should have a parameter to set a message
- [ ] other??
- [ ] notify PMM gatekeepers for what's new posts

**Comment by roadlittledawn** [comment]
@rhetoric101 || @daynaslord . Question for ya on this. 

Exactly when should a PMM be notified of a What's New post? When a docs-website collaborator makes a PR to `develop` and it contains a a file somehwere in `src/content/whats-new`?

And where in Slack should this notification go? A particular channel? DMs?

And what should the content of the notification be exactly? Should it mention anyone, contain any links (to the PR perhaps?), have some instruction / call to action?

**Comment by daynaslord** [comment]
Hi @roadlittledawn 

1. [Here](https://docs.newrelic.com/docs/style-guide/writing-docs/article-templates/whats-new-template/) are the instructions for folks to create a WN post for context. When collaborators [create a pull request (PR)](https://docs.newrelic.com/docs/style-guide/writing-docs/article-templates/whats-new-template/#create-pr) in src/content/whats-new/year/month/, I'd like for PMMs (me, Alexis Jones, and John Kinmonth) to be notified via Slack so that we can review and approve the PR.

2. This Slack notification should go to this channel - https://newrelic.slack.com/archives/C02SUERN3B5

3. The notification should mention Dayna Lord, John Kinmonth, and Alexis Jones and say something like - "Please review and approve [this pull request](link to the PR).

Let me know if you have any questions or concerns. Thank you!

**Comment by daynaslord** [comment]
QQ: No rush on this, but when do you think this will go live? @jpvajda @roadlittledawn

**Comment by roadlittledawn** [comment]
i think we'll try and get this into our next sprint (starts Jan. 18) as long as there's capacity. assuming it makes it in, sprints are two weeks and we'd try to have it deployed by end of sprint.

**Comment by daynaslord** [comment]
Sounds good - thank you for the update!

**Comment by daynaslord** [comment]
Hey Team @jpvajda @roadlittledawn - Hope you both are doing well. Is there an update on this?

**Comment by roadlittledawn** [comment]
Moved to jira https://newrelic.atlassian.net/browse/DOCENG-15
