### ISSUE TITLE
Issue: Python agent configuration

### ISSUE THREAD

**Issue by Greg-Myers-SB** [newrelic/docs-website#5479]
## How can we make our docs better?

The SSL config option is mentioned and linked from https://docs.newrelic.com/docs/apm/agents/python-agent/configuration/python-agent-configuration/#proxy as https://docs.newrelic.com/docs/apm/agents/python-agent/configuration/python-agent-configuration/#ssl
But there is no anchor there.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/python-agent/configuration/python-agent-configuration/
* **OS**: Pop_OS! 21.10
* **Browser**: Firefox
* **Device**: -

**Comment by urbiz-nr** [comment]
Checking with the team.

**Comment by urbiz-nr** [comment]
Closed via #5597. There's no replacement for the link, so I'm removing it.

**Comment by Greg-Myers-SB** [comment]
Thanks for the update, does this mean the SSL option is no longer available for the python agent?

**Comment by umaannamalai** [comment]
Hi @Greg-Myers-SB, popping in here from the Python Agent side! You are correct, SSL is no longer configurable in the Python Agent. This setting was deprecated in [v2.104.0.86](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-2104086/#mandatory-ssl) and has since been removed.  Therefore, SSL connections are now enforced and cannot be overridden. 

Thank you for filing for this issue! We will be updating the proxy config docs to reflect this setting change.
