### ISSUE TITLE
[Prototype] Create a framework for transforming migrated content

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#55]
## Summary

We may discover issues with the HTML when migrating the content from the existing docs site to MDX. Furthermore, there may be HTML snippets we need to convert from one format to another. We need to create the tools and the framework for generating codemods that we can run on all the MDX files.

## Acceptance criteria

- [ ] Can run a codemod on an MDX file and transform it
- [ ] Allow others to create custom codemods that can transform content in some way

**Comment by jerelmiller** [comment]
We still have some outstanding approaches to resolve to figure out the tooling we want for this. For example, [Turndown](https://github.com/domchristie/turndown) allows us to transform HTML -> Markdown, but this may not be flexible enough for our needs. We need to evaluate the tools MDX uses as well that transforms the MDX content into an AST, which we can then run transforms on. That approach is much more flexible but at the cost of added complexity.

**Comment by roadlittledawn** [comment]
Looks like turndown doesn't parse our `<pre>` blocks out of the box because it expects `<pre><code>...</code></pre>`. so the code blocks are just paragraph lines and gatsby mdx chokes on periods and curly brackets (because they're not parsed and escaped as part of code block). We'll likely be component-izing these anyway, but this tripped me up.

https://domchristie.github.io/turndown/

**Comment by zstix** [comment]
This was somewhat address in #66 (separating how we process docs by type), but we could still do some work to implement the actual "code mod" system.
