### ISSUE TITLE
Broken links in NuGet package descriptions

### ISSUE THREAD

**Issue by jamestul** [newrelic/docs-website#5717]
The links to help documentation in NuGet descriptions and Project URLs are broken for the following packages:

- NewRelic.Agent.Api
  - http://newrelic.com/docs/dotnet/AgentApi
  - https://docs.newrelic.com/docs/agents/net-agent/features/net-agent-api
- NewRelic.Azure.WebSites
  - https://newrelic.com/windowsazure
- NewRelic.Azure.WebSites.x64
  - https://newrelic.com/windowsazure

**Comment by paperclypse** [comment]
Hi @jamestul, thanks for writing in! I assume you're referring to these repos:

• https://github.com/newrelic/nuget-agent-api
• https://github.com/newrelic/nuget-azure-web-sites
• https://github.com/newrelic/nuget-azure-web-sites-x64

It looks like these repos are archived/read-only. I'm checking in with the .NET team about these. 

The docs team can't make edits to newrelic.com or these repos, but I'm happy to add a redirect for the Docs URL you listed.

**Comment by jamestul** [comment]
@paperclypse ah yes they're the ones. A redirect would be great thanks 👍

**Comment by nr-ahemsath** [comment]
@jamestul Hi, I work on the .NET agent team.  Those github repos you mentioned are an artifact of our team's previous release process from before we open-sourced the agent; we used to publish those sub-parts of our codebase publicly on every release.  However, we haven't done that since March 2018, which is why those repos are now archived.

It does appear that our latest published versions of those NuGet packages on NuGet.org have the same broken links; I have created an issue in the agent's repo to fix this: https://github.com/newrelic/newrelic-dotnet-agent/issues/883
