### ISSUE TITLE
Issue: following a link to a nested anchor within collapsible sections doesn't expand the section or focus on the section

### ISSUE THREAD

**Issue by throck** [newrelic/docs-website#5864]
## following an anchored link doesn't expand the section or focus correctly

e.g. when following [this link](https://docs.newrelic.com/docs/accounts/accounts/saml-single-sign/saml-service-providers/#bypassing) for the first time, neither the subsection in which it is contained ([Add users to SAML accounts](https://docs.newrelic.com/docs/accounts/accounts/saml-single-sign/saml-service-providers/#add-users-saml)) nor the target section nested within ([Bypass email confirmation](https://docs.newrelic.com/docs/accounts/accounts/saml-single-sign/saml-service-providers/#bypassing)) are expanded or brought into focus when following the link for the first time.  Both of these sections are under the [More SAML SSO procedures section](https://docs.newrelic.com/docs/accounts/accounts/saml-single-sign/saml-service-providers/#more-procedures)

If the page is already loaded,  and a nested section has been expanded, when reloading the page with an anchor, focus works correctly _but only for the first level nested section_

This behavior makes sharing links to nested anchored sections not very usable, as they don't direct the user to the desired target section in a page.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts/saml-single-sign/saml-service-providers/#bypassing
* **OS**: Mac OS
* **Browser**: Chrome 97.x
* **Device**: MBP

**Comment by zuluecho9** [comment]
@throck yes, thank you. This is a known issue, and we generally avoid putting links to headings inside of clamshells, because this doesn't work, as you've noticed. The reason these are like this in this doc is because it's the original user model docs, and they were recently consolidated in one place due to increasing deprecation of that user model, so they're a little rough around edges. I'll fix this one and see if there are any more like that in there I can fix. Thanks!

**Comment by zuluecho9** [comment]
Did work in https://github.com/newrelic/docs-website/pull/5865.
