### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by JonWebster** [newrelic/docs-website#6060]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/distributed-tracing/infinite-tracing
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Thanks for reporting this! We no longer have auto-index landing pages, which is why you are hitting a 404 here. To navigate through the docs site, you have to go to an actual doc such as the [intro to infinite tracing doc](https://docs.newrelic.com/docs/distributed-tracing/infinite-tracing/introduction-infinite-tracing).

With that said, I'll add a redirect from that 404 to the intro to doc I linked above!
