### ISSUE TITLE
Localization Pre-MMF research

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#61]
As we migrate the docs site to gatsby we need to define our approach for localization for the new site. This task is to do some preliminary investigation into how we will approach localization short term and long term.

### Short Term 

- Evaluate the current technology approach with the Drupal site to see if there is a way to use the existing vendor solution for our localization approach with the new site. 

###  Long Term 

- Evaluate the long term technology approach and determine an iterative way to move forward.

**Comment by caylahamann** [comment]
Some research from this morning: 

I found [a repo](https://github.com/onelink-translations/react-localization) from OneLink that uses the proxy and React to localize content on the page. It seems from this it is possible to first implement with OneLink for the short-term, then eventually have our website conditional render from Smartling, and then eventually have Smartling implement with Github. The repo uses `react-intl` for localization and provides the content via a context provider. 

-

**Comment by zstix** [comment]
@caylahamann Sorry for being so late to coming back to this.

Do you know if we _need_ a backend server to make the proxy work? Due to the docs site being static, we wont have the ability to anything with [express-request-language](https://github.com/tinganho/express-request-language).

If we don't know, we can build that research into our MMF.

**Comment by jpvajda** [comment]
This is SO DONE. 😄
