### ISSUE TITLE
Present the "stitched path" link buttons better that will allow user to learn more about getting data into new relic

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#621]
Stiched path buttons are the term used for buttons that allow a user to learn how to get data into new relic. and example can be found on this [kubernetes page](https://docs-preview.newrelic.com/docs/integrations/kubernetes-integration/get-started/introduction-kubernetes-integration)

and this [prometheus page](https://docs-preview.newrelic.com/docs/integrations/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic)

### UX Considerations

- do we have a component we can leverage from any other cool UI projects?
- Could this be more of checklist component, that walks the user through the steps?
-  If you're going to replace the first item with a checkbox once someone has logged in, I wouldn't use numbered bullets (since otherwise it'll look weird to have ✓, 2, 3, ...)
- Are the steps always linear? For example, if you're familiar with the docs already, you might go straight from sign in to the install step. Perhaps give optional steps an (optional) modifier or omit them entirely (you could also combine each docs link into the same step as the action it relates to, so it's clear what the outcome of reading the docs will be).
 - When someone clicks one of these links, do you want to open the link in a new tab so they don't lose their context? If so, consider adding an external link icon to make this behavior clear.

<img width="509" alt="Screen Shot 2021-01-21 at 5 53 55 PM" src="https://user-images.githubusercontent.com/1395158/105431120-38614e80-5c12-11eb-953c-638472c87bea.png">

<img width="884" alt="Screen Shot 2021-01-21 at 5 48 18 PM" src="https://user-images.githubusercontent.com/1395158/105431113-34cdc780-5c12-11eb-9df6-f02aecc3188f.png">

## UX Mock Up

<img width="548" alt="Screen Shot 2021-01-26 at 3 51 50 PM" src="https://user-images.githubusercontent.com/1395158/105916643-7681b800-5fee-11eb-9b98-13ffaafe2f6a.png">

**Comment by jpvajda** [comment]
I've reached out to some XD peeps for some suggestions.

**Comment by djsauble** [comment]
Few thoughts:

* If you're going to replace the first item with a checkbox once someone has logged in, I wouldn't use numbered bullets (since otherwise it'll look weird to have ✓, 2, 3, ...)
* Are the steps always linear? For example, if you're familiar with the docs already, you might go straight from sign in to the install step. Perhaps give optional steps an `(optional)` modifier or omit them entirely (you could also tie each docs link to the action you're trying to get each person to take, so it's clear what the outcome of reading the docs will be).
* When someone clicks one of these links, do you want to open the link in a new tab so they don't lose their context? If so, consider adding an external link icon to make this behavior clear.

**Comment by jpvajda** [comment]
Marking as won't do I found out virtouso will replace this functionality so no point in building something we'd eventually replace.

**Comment by jpvajda** [comment]
@austin-schaefer  / @zstix  just an FYI on why I marked this as `wont do`
