### ISSUE TITLE
I'm not seeing Create an issue or edit this page buttons

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#639]
For some reason, I'm not seeing the Create an issue or Edit this page buttons. 

Also, logging in doesn't seem to help.

**Comment by jerelmiller** [comment]
@paperclypse are there specific pages that you expect to see it and don't? No login required for the new docs site since it doesn't use authentication in any capacity yet.

We have the GitHub buttons in both the footer and the docs pages right rail. Not all content have the right rail component. 

After visiting a couple docs, I see those buttons just fine. Here are some examples:

* https://docs-preview.newrelic.com/docs/apm/transactions/key-transactions/introduction-key-transactions
* https://docs-preview.newrelic.com/docs/browser/browser-monitoring/getting-started/browser-summary-page

For pages without the right rail, you'll find it in the footer:

<img width="1297" alt="Screen Shot 2021-01-25 at 1 18 39 PM" src="https://user-images.githubusercontent.com/565661/105767402-db1a1580-5f0f-11eb-9f1f-ef06f30b41c2.png">

If you still aren't seeing it, could you paste a couple links in here so that we can take a look?

**Comment by paperclypse** [comment]
I feel pretty silly now, @jerelmiller! I think that I wasn't seeing the right nav because my browser window was too narrow.
