### ISSUE TITLE
Surface data dictionary in site search, Google

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#6584]
## Is your feature request related to a problem? Please describe

We noticed that the data dictionary entries are not visible via docs site search or via search engines like Google, DuckDuckGo 

## Describe the solution you'd like

We thought it would be cool if, at the very least, the data types (e.g., TransactionError, NrAiSignal, PageView) show up in the docs site search and also in search engine search results. And possibly the attribute names also (although there might be too many of these and possibly it will result in too many similar, competing search results so good chance that wouldn't be a good idea, or possibly just something to do for the most popular attribute entries). We'd like to investigate what a solution might look like for the docs site search and public search. 

## Describe why this important to you

Customers sometimes want to understand a specific data type better and one way they'll do this is by searching docs site or public search for a specific data type name. Be nice to get them directly to those results. 

Related to https://github.com/newrelic/docs-website/issues/5084

**Comment by paperclypse** [comment]
It's worth noting that even the data dictionary isn't searchable: https://docs.newrelic.com/attribute-dictionary

**Comment by roadlittledawn** [comment]
yeah, historically it's a tricky one. historically, we've excluded data dictionary from search because it could add a lot of noise, esp in swiftype searches.

and technically (at least from swiftype's perspective) there are many unique URLs for that page (when you add query params), so we'd have to limit the index to just the one page with all events/attributes. 

we may be able to do that and add some precise tagging to only let swiftype index event names as part of the body of the record so queries would only match against those.

**Comment by roadlittledawn** [comment]
@zuluecho9 @paperclypse filed this issue. let me know if that would meet the need IYO. https://github.com/newrelic/docs-website/issues/6657

**Comment by roadlittledawn** [comment]
closing in favor of jira
