### ISSUE TITLE
Issue: Telemetry SDKs: Report custom telemetry data

### ISSUE THREAD

**Issue by kaizer113** [newrelic/docs-website#7168]
the link under 
"Under the hood, these SDKs rely on our primary [data ingest APIs](https://docs.newrelic.com/docs/data-apis/ingest-apis): "

just reloads the same page

**Comment by rhetoric101** [comment]
@kaizer113, thanks for the heads-up about this self-referential link! I think this used to point to an outdated table of contents page that listed all the New Relic APIs. Since that no longer exists, I simply removed this link. I appreciate your help keeping the docs up to date!

PR #7172 addresses this link issue.
