### ISSUE TITLE
Issue: Configure the New Relic Gradle plugin

### ISSUE THREAD

**Issue by tommos23** [newrelic/docs-website#7897]
## How can we make our docs better?

* Something inaccurate or missing?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-new-relic-gradle-plugin/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

`uploadMapsForVariant` and `excludeVariantInstrumentation` are marked as deprecated in 6.6.0
Have these functions been replaced with `shouldIncludeMapUpload` and `shouldExcludeVariant` ?

**Comment by zuluecho9** [comment]
@tommos23 Hi Aaron. Here is a message about this from the product team: "no, uploadMapsForVariant and excludeVariantInstrumentation are deprecated, as a long term warning message, these functions will be changed in future releases. And they are not replaced with shouldIncludeMapUpload and shouldExcludeVariant , they are different methods." Hopefully this helps.

**Comment by JCapriotti** [comment]
I came across this issue because the docs for configuring the New Relic Gradle plugin say to use `uploadMapsForVariant`, which as mentioned above is deprecated. 

Can this issue be reopened so that the docs are updated to be reflect the current version of the plugin? I'm assuming using `uploadMapsForVariant` is not a current recommendation?
