### ISSUE TITLE
[Tessen] Add tessen events for stitched paths and doc views 

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#790]
## Summary
Once we have tessen set up, we need to set up the events to reach parity with the current docs site. There are only two events that we need to instrument with tessen: 
* Page view => we send this each time a visitor goes to one of our pages 
* Stitched path => we send this whenever a visitor clicks on the "create a free account" button 

## AC 
* [x] Instrument page views 
* [x] Instrument stitched path 

## Helpful links: 
* [this spreadsheet](https://docs.google.com/spreadsheets/d/1VmgEp4n-GA3wvIjBy7rJQn3H7k_ytoqxvYG50X8xeAs/edit?usp=sharing) has the exact names for these events

**Comment by caylahamann** [comment]
`data` attribute on these events - check out what information is in here and what we need to add to our event

**Comment by jpvajda** [comment]
just to be clear, a stitched path is not an account creation , it's actually this: 

https://github.com/newrelic/docs-website/issues/621

**Comment by jpvajda** [comment]
Actually they both are stiched paths, I stand corrected.

**Comment by jpvajda** [comment]
User reads content about [data source] on docs/blog/storefront > User gets added to [data source] audience in Optimizely > User creates an account and gets custom content about [data source] on the sign up pages (for a couple data sources) > Data enters NR1 and is immediately forwarded to [data source] install page instead of homepage.

**Comment by zstix** [comment]
Page views are now being tracked: https://github.com/newrelic/docs-website/blob/develop/gatsby-config.js#L135-L142
