### ISSUE TITLE
The "Install for Windows" .NET left nav link doesn't work

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#803]
### Description

For some reason, the .NET "Install for Windows" link in the left nav doesn't work.

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/agents/net-agent/installation/introduction-net-agent-install
2. Click on **Install for Windows** in the left nav.
3. Watch it not work.

### Expected behavior

That link should go to this doc: https://docs.newrelic.com/docs/agents/net-agent/installation/install-net-agent-windows

Maybe it got missed in the migration?

**Comment by jerelmiller** [comment]
It appears this link was [added as a redirect](https://raw.githubusercontent.com/newrelic/docs-website/develop/src/content/docs/agents/net-agent/installation/introduction-net-agent-install.mdx) to that introduction page. I see that the page [also exists](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/agents/net-agent/installation/install-net-agent-windows.mdx). I believe the redirect in this case is "winning". We'll need to check out our migration script and see why we are getting a redirect for that page because that definitely shouldn't be listed.

**Comment by roadlittledawn** [comment]
yep, it's a redirect. digging in now

**Comment by roadlittledawn** [comment]
Looks like a rare case where the redirect was created then later disabled. Deleting that redirect now so migration script doesn't pick it up

**Comment by jerelmiller** [comment]
@roadlittledawn do you have the ability to check if this is the case for other redirects? Would love to nuke all the duplicates if a page exists at a redirect.
