### ISSUE TITLE
Issue: Error inbox limit reached - please add doc for error group limits

### ISSUE THREAD

**Issue by khickey-newrelic** [newrelic/docs-website#8544]
## How can we make our docs better?

What is the error group limit?  Can we add it here: https://docs.newrelic.com/docs/data-apis/manage-data/view-system-limits/#all_products and link back to it?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/errors-inbox/error-limiting
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by zuluecho9** [comment]
might be obvious, but in case helpful for later hero taking this: 

path I would take would be pinging an errors inbox SME about the limit, adding that to our system limits doc, and finding a place in errors inbox doc to reference that limit.

Because I'm liaison of the data limits area, let me know if you have any questions.

**Comment by zuluecho9** [comment]
thanks @khickey-newrelic !

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
