### ISSUE TITLE
TDP, FSO, AI "table of contents" pages are generating with no content

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#877]
NOTE: This is occurring on the following pages when clicking on the  `View all button`

[TDP](https://docs-preview.newrelic.com/docs/telemetry-data-platform) > https://docs-preview.newrelic.com/docs/telemetry-data-platform/table-of-contents
[FSO](https://docs-preview.newrelic.com/docs/full-stack-observability) > https://docs-preview.newrelic.com/docs/telemetry-data-platform/table-of-contents
[AI](https://docs-preview.newrelic.com/docs/alerts-applied-intelligence) > https://docs-preview.newrelic.com/docs/alerts/table-of-content

### Expected

when a user clicks on this button, we should echo out all links in the navigation of that section. similar to how it's currently working on the [.net agent TOC](https://docs-preview.newrelic.com/docs/agents/net-agent/table-of-contents)

**Comment by austin-schaefer** [comment]
Flagging this as a launch blocker, would be good to track this down ahead of launch.

**Comment by barbnewrelic** [comment]
I **think** (based on some Drupal stuff I was doing last week), if a "table of contents" is being built from a boatload of dummy doc redirects, we may not have any control over this. Unless we go into Drupid, track down the dummy doc, and force it into some kind of order that we want for a newly new TOC in GitHub.

**Comment by jpvajda** [comment]
relates to the explaination here: https://github.com/newrelic/docs-website/issues/566

**Comment by jpvajda** [comment]
Not really a "bug" but we'll have to consider  

to Only create auto generated pages for URLs that have a matching nav item

Currently we have quite a few nav items that only act as toggles for a set of grouped links. One possibility would be to add a path to these. From here, we could analyze all of the links in navs that do not have an authored page and auto generate the page. Because we would now have a path to match against, we can easily pull the nav for that auto generated page.

**Comment by jpvajda** [comment]
actually this a bug we found in some of the button link references.

**Comment by barbnewrelic** [comment]
I moved some Insights docs last week, which left some of the Drupal taxonomy empty. At this point should I delete/redirect in Drupal or just wait until after the migration? Deleting taxonomy L2s and L3s in Drupal always makes me nervous, so I wanted to double-check with you before I do this. I asked about this last week but I know you all have been crazy busy with other stuff.
<img width="1177" alt="insights-taxonomy-drupal022421" src="https://user-images.githubusercontent.com/1672581/109198775-77c01500-7753-11eb-9c32-c3091b923472.png">

**Comment by jpvajda** [comment]
@barbnewrelic I think we can correct after the migration freeze, cc @jerelmiller  agree?

**Comment by jpvajda** [comment]
@barbnewrelic it has nothing to do with drupal, we think it's a bug in a plugin

**Comment by barbnewrelic** [comment]
ok. i just didn't want to lose this piece of info because it's one more part of taxonomy mismatch. sorry!

**Comment by jerelmiller** [comment]
Yep, just to weight in a bit on the technical side, as @jpvajda mentioned, this looks like a bug in our plugin that generates those table of contents pages. Really the only thing that drupal would affect at this point is how the nav is organized when we migrate. The table of contents pages are auto-generated behind the scenes so that as pages get created/deleted/moved around, we don't need someone to maintain them. 

I suspect its just the top-level links with landing pages don't get a table of contents page with the right data. I have been able to visit a subnav landing page and get to a table of contents page full of links as we expect (e.g. https://docs-preview.newrelic.com/docs/apm/table-of-contents), so its at least partially working.

**Comment by jerelmiller** [comment]
Will be fixed with https://github.com/newrelic/docs-website/pull/990
