### ISSUE TITLE
when more than 1 release note is posted in a single day, we aren't sorting them correctly

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#910]
Check the timestamp on the python release note example where they are out of order. We want to be sure that 2 or more releases post in the correct order based on their version number

![Screen Shot 2021-02-18 at 5 21 28 PM](https://user-images.githubusercontent.com/1395158/108439220-12799a80-720e-11eb-858e-237c90509733.png)

**Comment by jerelmiller** [comment]
To add some context here, we are only migrating dates and not the release time. We advocated for removing the time from the release date because that field is a human-defined field. Time is only used as a sorting mechanism as a tie-breaker in the event dates are the same. Again, we advocated for removing time to make it easier on a content contributor creating a new release note.

I wonder if maybe we use the versioning as the tie breaker in this case. Since `6.0.1.155` comes after `6.0.1.154`, we could leverage that instead. This is a pretty rare occurrence however, so we're not in dire need to fix this immediately.
