### ISSUE TITLE
Broken TDP Table of Contents

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#931]
## Description

The [table of contents page for TDP](https://docs-preview.newrelic.com/docs/telemetry-data-platform/table-of-contents) does not seem to be working. This seems pretty important since it is useful for users scanning the entire categories. 

## Steps to Reproduce

1. Click https://docs-preview.newrelic.com/docs/telemetry-data-platform/table-of-contents

## Expected Behavior

I expect the page to be an index of all the TDP docs.

## Additional context

[NOTE]: # (PLEASE DO NOT DELETE THIS SECTION. This contains useful information for the team.)

### Page
https://docs-preview.newrelic.com/docs/telemetry-data-platform/table-of-contents

### Environment
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
I see @barbnewrelic has created a similar issue for the insights TOC #877

**Comment by barbnewrelic** [comment]
I **think** (based on some Drupal stuff I was doing last week), if a "table of contents" is being built from a boatload of dummy doc redirects, we may not have any control over this. Unless we go into Drupid, track down the dummy doc, and force it into some kind of order that we want for a newly new TOC in GitHub.

**Comment by jpvajda** [comment]
I believe there is an explaination for this that relates to, and maybe @barbnewrelic is right, but these pages aren't really intended to be part of the site navigation. they exist due to how we structured the URLs for migration but perhaps @jerelmiller can explain: this issue also goes into it:  https://github.com/newrelic/docs-website/issues/566

**Comment by jpvajda** [comment]
as part of #566 we are consider to Only create auto generated pages for URLs that have a matching nav item

Currently we have quite a few nav items that only act as toggles for a set of grouped links. One possibility would be to add a path to these. From here, we could analyze all of the links in navs that do not have an authored page and auto generate the page. Because we would now have a path to match against, we can easily pull the nav for that auto generated page.

**Comment by jpvajda** [comment]
closing as a duplicate this will be fixed in #877
