### ISSUE TITLE
[Bug Bash] "Step" CTAs on the home page do not open in a new tab

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#939]
## Description
The 3 "step" tiles on the homepage are external links, but they open in the same tab. We should consider opening them in new tabs so that the user is not abruptly taken away from the docs site.

**Comment by jpvajda** [comment]
I was working on this over the weekend and tried 

```
 <WelcomeTile
              to={window.open('https://newrelic.com/signup', '_blank')}
              title={t('home.welcome.t1.title')}
              description={t('home.welcome.t1.description')}
              variant="cta"
            />
```

but am getting window not defined when running locally, I assume it's because in local there is no "window" when running node locally, I'm just curious if there is a better approach. 🤔

**Comment by jerelmiller** [comment]
@jpvajda looking at this a bit more, I think this is actually simpler than that.

It looks like the props to `WelcomeTile` are what we expect. They have links to pages as we expect them to. The problem is that we are using the wrong set of props in the implementation of the `WelcomeTile` itself. If you [trace that component](https://github.com/newrelic/docs-website/blob/develop/src/pages/index.js#L323), you'll end up at [`SurfaceLink`](https://github.com/newrelic/docs-website/blob/develop/src/components/SurfaceLink.js) which is what is used under the hood.

You'll see the following implementation:

```js
const SurfaceLink = ({ to, ...props }) => {
  const isRelativeLink = to.startsWith('/');
  const linkProps = isRelativeLink
    ? { to }
    : { href: to, rel: 'noopener noreferrer' };

  return (
    <Surface
      {...props}
      {...linkProps}
      as={isRelativeLink ? Link : 'a'}
      interactive
    />
  );
};
```

Notice here how we are checking if the `to` prop is a relative link or an external link. If its a relative link, then we use the `Link` component and give it the `to` prop (via `linkProps`). If its an external link, we give it a regular anchor tag and set the `href` and `rel` props. But you'll see that we aren't setting the `target="_blank"` prop when using a regular anchor, hence why the link doesn't open in a new tab.

Since this component has been implemented, the `Link` component has been updated to handle both relative and external links. Rather than having this component check with its relative or external, we can simplify and use `Link` everywhere. `Link` will automatically open external links in a new tab.

Here is how I'd update the implementation:

```js
const SurfaceLink = ({ to, ...props }) => {
  return (
    <Surface
      {...props}
      as={Link}
      to={to}
      interactive
    />
  );
};
```
