### ISSUE TITLE
Lambda not working, not receiving logs

### ISSUE THREAD

**Issue by victoruyy** [newrelic/docs-website#9798]
Can't install it, after deploying it, and creating the lambda trigger I am not receiving any logs at all on the platform, the documentation is so confusing
The platform requires a lot of things to configure and get it working, asking me to integrate other AWS Services like kinesis, etc

I was able to see some "logs" but it were cloudwatch metric logs in plain text, with a lot of horrible symbols, can't read it properly

Really not nice experience,
Hope I can be assisted,

Thank you

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 106.0.0.0
* **Device**: Unknown

**Comment by akristen** [comment]
Hi @victoruyy! I'm sorry about that frustrating experience! I'm following up with our Lambda tech support and I'll have them reach out to you here, so you can coordinate and get everything set up correctly.

**Comment by keegoid-nr** [comment]
@victoruyy thank you for sharing your experience here! We appreciate knowing when something is too confusing.

We are actually in the process of some docs updates, because we know it is confusing in its current state.

Sounds like you went through the process of setting up a [Metric Streams integration](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup/)? Did you happen upon our [CloudFormation template](https://console.aws.amazon.com/cloudformation/home?#/stacks/quickcreate?templateURL=https://nr-downloads-main.s3.amazonaws.com/cloud_integrations/aws/cloudformation/MetricStreams_CloudFormation.yml&stackName=NewRelic-Metric-Stream&param_NewRelicDatacenter=US) that eases this process?

I see you've followed the [log ingestion doc](https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs/) to forward CloudWatch Logs to New Relic. I'm not certain a Metric Streams integration is needed just to forward logs to New Relic. I see no mention of it in that doc. Our [aws-log-ingestion](https://github.com/newrelic/aws-log-ingestion) repository contains more details on various deployment methods.

Part of the confusion is determining which docs to follow based on what one wants to see in New Relic.

1. Is your goal to get CloudWatch Logs into New Relic so you can view them in the **Logs** UI?
1. We also have a set of docs for [Lambda Monitoring](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/monitoring-aws-lambda-serverless-monitoring/) where a Lambda function is instrumented with our Lambda layer in order to get detailed metrics into New Relic. This includes Lambda function logs and Logs in Context for each invocation. Either an API polling or Metric Streams integration is needed for this to work.

About the unformatted and unwieldy logs, it might be due to the format the logs are sent with. Are they "stringified" or or invalid JSON? We might [have trouble parsing](https://docs.newrelic.com/docs/logs/troubleshooting/json-message-not-parsed/) them in that case.

@djzevenbergen Anything else you think could be helpful to know here?

**Comment by victoruyy** [comment]
Hi Keegan, how are you? thank you for assisting me, 

Exactly, as you mentioned I went through the process of metrics steams with your cloudformation template that implemented it in a second, and that works nice I think, if I go to infrastructure -> AWS I am able to
 see there some suffs, general metrics, regarding 

![Screen Shot 2022-10-14 at 14 35 08](https://user-images.githubusercontent.com/22249283/195907770-e7369bb2-09b3-4015-9858-2f3245583dc9.png)

but my goal is to be able to see here the logs of my ECS application

![Screen Shot 2022-10-14 at 14 38 29](https://user-images.githubusercontent.com/22249283/195907931-9b7f3545-243c-4da9-bb1a-d1994908e303.png)

I've used that repo you mentioned to deploy it through terraform, but it didn't work, then I tried manually, but same thing.


**Is your goal to get CloudWatch Logs into New Relic so you can view them in the Logs UI?**

- YES 

**About the unformatted and unwieldy logs, it might be due to the format the logs are sent with. Are they "stringified" or or invalid JSON? We might [have trouble parsing](https://docs.newrelic.com/docs/logs/troubleshooting/json-message-not-parsed/) them in that case.**

- They looked like JSONs yes, but anyway these logs that I was receiving it were the metrics one from Kinesis, but in plain text, really weird behaviour

I don't think that Kinesis will be my goal here, I would like to see the same logs that I am actually seeing in CloudWatch for the application only, but in NewRelic, so I can take advantage of the NR features to see and understand where is the problem of the application, and debug there

Right now, after my lambda function creation, I've created the trigger and nothing else, the logs are not coming to the NR platform, even if I already added the License KEY environment variable

Much appreciated, 

Thank you

**Comment by keegoid-nr** [comment]
@victoruyy, thank you for your time and effort to provide those details!

We have two ECS integrations: on-host and cloud-based. For the most comprehensive view on ECS and the services running on ECS, we recommend implementing both. However, it is the Infrastructure agent that ships logs from ECS. I don't think you will need the log ingestion function at all.

- [host-based with Infra agent](https://docs.newrelic.com/docs/infrastructure/elastic-container-service-integration/introduction-amazon-ecs-integration/)
- [cloud-based](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-ecsecr-monitoring-integration/)

For the cloud-based integration, if since you've already set up your streams integration, there's nothing more to do. Just ensure that you've selected the ECS namespace for sending via the metric stream in the AWS console.

For logs, I suspect you will next need to [host-based integration](https://docs.newrelic.com/docs/infrastructure/elastic-container-service-integration/install-ecs-integration/#cloud-formation-install) and then configure the Infrastructure agent to ship logs.

Here's how to forward logs using the [Infrastructure agent](https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent/).

None of the above would involve Lambda unless you want to send CloudWatch logs to New Relic. However, as you've noticed, CloudWatch logs probably do not contain ECS logs. What you are seeing are probably just logs from the metric stream itself.

**Comment by victoruyy** [comment]
Hey @keegoid-nr, thank you for all the information provided and the help so far.

Actually, the log ingestion feature is not enabled in fargate, so installing the agent on the ECS won't be worth it. Only to see metrics will be useful.
I managed to get the logs from CloudWatch to NR platform via [lambda](https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs/) as it was one of my first intentions.. anyway ... I couldn't realize about what was going on because the env variable that enable the logging was disabled by default ... `LOGGING_ENABLED` 

**Please .. specify and put in the page that this is a very important variable and need to be set to true in order to receive any logs, from the beginning, I think this is a very important point**

Thank you very much,
Cheers
