### ISSUE TITLE
Surprising number of broken links (possibly dummy doc related?)

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#980]
### Description

The smoke test—less than an hour, and just some random browsing—turned up a surprisng number of broken links. I'd like to understand the root cause here (dummy docs? taxonomy moves?) and resolve before we release.

I think it's less that we need to catch every last broken link, and more that we need to figure out why so many are still occurring and the remediate whatever the pattern(s) end up being.

A few examples:

* Amazon AWS integrations gets a 404 : https://docs-preview.newrelic.com/docs/infrastructure/integrations/integrations/amazonaws-integrations-0 
* Azure integrations gets a 404 : https://docs-preview.newrelic.com/docs/infrastructure/integrations/integrations/azure-integrations 
* On-host integrations gets a 404 : https://docs-preview.newrelic.com/docs/infrastructure/integrations-getting-started/integrations/host-integrations 
* On the Alerts and AI landing page, in the Define alert conditions tile, the REST API link is broken. 
* Redirect not working: this link https://docs-preview.newrelic.com/docs/query-data/nrql-new-relic-query-language/query-tools/chart-builder-create-query-visualizations/ should redirect to this page: https://docs.newrelic.com/docs/query-your-data/explore-query-data/query-builder/introduction-query-builder
* This link in the left nav is broken and returning a 404: https://docs-preview.newrelic.com/docs/alerts/new-relic-alerts/defining-conditions/create-infrastructure-host-not-reporting-condition/  
* CPM release notes 404  https://docs-preview.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/containerized-private-minions-cpm-release-notes 
* There’s a 404 resulting when I try to load https://docs-preview.newrelic.com//docs/data-ingest-apis/get-data-new-relic/metric-api/ 

### Expected behavior

No links or URLs that work in the current site are broken in the new site.

**Comment by jerelmiller** [comment]
After doing a quick dive to try and understand why this might be the case, it looks like these are redirects to auto generated index pages. We have a [file](https://github.com/newrelic/docs-website/blob/develop/src/data/taxonomy-redirects.json) that tracks all of the taxonomy redirects, but checking just a handful of these links above don't appear to be in that taxonomy redirects file. Not sure if these were dropped during the migration or what. Will dig into this further to understand why the redirects are missing.

If worse comes to worse, it looks like the top few are only linked from the nav, so we can replace the nav links with the new path instead of the redirected one (though hard to tell how widespread this issue is right now)

**Comment by jerelmiller** [comment]
Ah yes, could also be dummy doc related. Perhaps our migration script detected dummy docs, but did not handle these as taxonomy redirects? 🤔 . Thats where I think would be a good place to start 😄

**Comment by roadlittledawn** [comment]
i haven't dug in super close to this yet, but if a dummy doc links to what was a taxonomy page (an index page in Gatsby), it may not get automatically created if:
- the redirect is to a page in `docs/release-notes` or `whats-new`
- the redirect is to an existing index.mdx file (that was applied via `manual-edits`). we had to add those manually to those files.
- the migration script can't find a target URL path that matches the file path in Gatsby

**Comment by roadlittledawn** [comment]
yeah i think it's some atypical looking dummy docs, the infra/integrations are especially gnarly. this one for example: 
https://docs-preview.newrelic.com/docs/infrastructure/integrations/integrations/amazonaws-integrations-0

that's a [dummy doc](https://docs.newrelic.com/node/13796/edit) with a redirect to `taxonomy/term/6981` which doesn't exist anymore. there's a redirect from `taxonomy/term/6981` to taxonomy/term/7921` (`docs/integrations/amazon-integrations/aws-integrations-list`), but since we can't get data (namely the URL path) on `6981` we don't create the redirect.

so yeah, chains of redirects where terms may no longer exist may not be migrated 100%

**Comment by jerelmiller** [comment]
That would do it. I'm hoping its only a handful of these like listed above. If so, we can manually fix these by adding the redirect path to the `redirects` front matter.

**Comment by zstix** [comment]
We've identified `17` links that are returning `404` responses. Since this is within range to manually set up redirects (rather than automate), we're going to address those one-by-one. We've got a spreadsheet that we're working through internally in collaboration with the docs team.

**Comment by jpvajda** [comment]
Add how to fix broken redirect link in the Contributor FAQ Trouble shooting.
